import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=90233%3A4905",
  {
    props: {
      items: figma.children('*')
      // variant is unsupported for now
      // variant: figma.enum("Variant", {
      //   "2+ lines": "2--lines",
      //   "1 line": "1-line",
      //   Title: "title",
      // }),
    },
    example: (props) => html`
      <ifx-action-list aria-label="Example Action List">
        ${props.items}
      </ifx-action-list>
    `,
  },
)
