import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

//  Action List Item component
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89898%3A5544",
  {
    props: {
      title: figma.nestedProps('_List Text', {
        title: figma.string('Title'),
        description: figma.boolean('Show Description', {
          true: figma.string('Description 1'),
          false: undefined,
        }),
      }),
      
      leading: figma.boolean('Show Leading Icon', {
        true: figma.children('_Leading'),
        false: undefined,
      }),
      trailing1: figma.boolean('Show Trailing Item 1', {
        true: figma.children('_1st Trailing'),
        false: undefined,
      }),
      trailing2: figma.boolean('Show Trailing Item 2', {
        true: figma.children('_2nd Trailing'),
        false: undefined,
      }),

      // Existing variables in Figma (autogenerated):
      // condition is not supported
      // condition: figma.enum("Condition", {
      //   "2+ lines": "2--lines",
      //   "1 line": "1-line",
      //   Title: "title",
      // }),
      // showOverline: figma.boolean("Show Overline"), // not supported by code
      // showLeadingIcon: figma.boolean("Show Leading Icon"),
      // showTrailingItem1: figma.boolean("Show Trailing Item 1"),
      // showTrailingItem2: figma.boolean("Show Trailing Item 2"),
      // leading: figma.enum("Leading", {
      //   Initials: "initials",
      //   "Image square": "image-square",
      //   "Image round": "image-round",
      //   Checkbox: "checkbox",
      //   Switch: "switch",
      //   Icon: "icon",
      //   None: "none",
      // }),
    },
    example: (props) => html`<ifx-action-list-item
        item-title=${props.title.title}
        description=${props.title.description}
      >
      <div slot="leading">${props.leading}</div>
      <div slot="trailing">${props.trailing1}</div>
      <div slot="trailing">${props.trailing2}</div>
    </ifx-action-list-item>`,
  },
)

// Sub components for Action List Item (Leading, Trailing 1, Trailing 2)
// They are connected separately, but just pass through the children to the main component as shown in the example above

// ActionListItem - _List Text
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89898%3A5492",
  {
    props: {
      title: figma.string("Title"),
      description: figma.boolean("Show Description", {
        true: figma.string("Description 1"),
        false: undefined,
      }),
    },
    example: (props) => html`<ifx-action-list-item item-title=${props.title} description=${props.description}></ifx-action-list-item>`,
  },
)

// ActionListItem - _1st Trailing
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89898%3A5450",
  {
    props: {
      content: figma.children("*"),
    },
    example: (props) => html`${props.content}`,
  },
)

// // ActionListItem - _2nd Trailing
// figma.connect(
//   "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89898%3A5471",
//   {
//     props: {
//       icon: figma.instance("Icon"),
//       trailing2: figma.enum("Trailing 2", {
//         Checkbox: "checkbox",
//         Button: "button",
//         "Icon button": "icon-button",
//         Icon: "icon",
//         Indicator: "indicator",
//         Status: "status",
//         Switch: "switch",
//         Text: "text",
//       }),
//     },
//     example: (props) => html`<ifx-action-list-item></ifx-action-list-item>`,
//   },
// )

// ActionListItem - _Leading
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89898%3A5529",
  {
    props: {
      content: figma.children("*"),
    },
    example: (props) => html`${props.content}`,
  },
)

