import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=63969%3A1780",
  {
    props: {
      children: figma.children("_Content Switcher"),
    },
    example: (props) => html`<ifx-content-switcher> 
      ${props.children}
    </ifx-content-switcher>`,
  },
)

// IfxContentSwitcherItem
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=63857%3A5836",
  {
    props: {
      labelText: figma.boolean("Show Label Text", {
        true: figma.string("Label Text"),
        false: undefined
      }),
      icon: figma.boolean("Show Icon", {
        true: html`<ifx-icon icon="grid-layout-16">`, // Figma needs to be adjusted to allow using the actual icon name from the instance
        false: undefined
      }),
      selected: figma.enum("State", {
        "Selected": true
      })
    },
    example: (props) => html`<ifx-content-switcher-item selected=${props.selected} value="unique-value">
      ${props.icon}
      ${props.labelText}
    </ifx-content-switcher-item>`,
  },
)