# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/components"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/components"
    schedule:
      interval: "daily"
    update:
      - package-name: "@infineon/infineon-icons"
        versions: ">=1.1.7"
  - package-ecosystem: "npm"
    directory: "/packages/components-react"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/components-vue"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/components-angular"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
