import "./App.css";
import "prismjs/themes/prism.css";
import Prism from "prismjs";
import { useEffect, useState } from "react";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-tsx";

// @ts-expect-error
import packageJson from "../package.json";

const declaredVersion = (packageJson.dependencies as Record<string, string>)[
	"@infineon/infineon-design-system-react"
];

import { version as installedVersion } from "@infineon/infineon-design-system-react/package.json";

/* <AUTO-GENERATED-IMPORTS> */
import { IfxAccordionExample } from './generated/IfxAccordionExample';
import { IfxActionListExample } from './generated/IfxActionListExample';
import { IfxAlertExample } from './generated/IfxAlertExample';
import { IfxAiLabelExample } from './generated/IfxAiLabelExample';
import { IfxButtonExample } from './generated/IfxButtonExample';
import { IfxCardExample } from './generated/IfxCardExample';
import { IfxCheckboxExample } from './generated/IfxCheckboxExample';
import { IfxCheckboxGroupExample } from './generated/IfxCheckboxGroupExample';
import { IfxChipExample } from './generated/IfxChipExample';
import { IfxContentSwitcherExample } from './generated/IfxContentSwitcherExample';
import { IfxDatePickerExample } from './generated/IfxDatePickerExample';
import { IfxDropdownExample } from './generated/IfxDropdownExample';
import { IfxFooterMediumExample } from './generated/IfxFooterMediumExample';
import { IfxIconButtonExample } from './generated/IfxIconButtonExample';
import { IfxIndicatorExample } from './generated/IfxIndicatorExample';
import { IfxLinkExample } from './generated/IfxLinkExample';
import { IfxNavbarExample } from './generated/IfxNavbarExample';
import { IfxSidebarExample } from './generated/IfxSidebarExample';
import { IfxNotificationExample } from './generated/IfxNotificationExample';
import { IfxPaginationExample } from './generated/IfxPaginationExample';
import { IfxProgressBarExample } from './generated/IfxProgressBarExample';
import { IfxRadioButtonExample } from './generated/IfxRadioButtonExample';
import { IfxRadioButtonGroupExample } from './generated/IfxRadioButtonGroupExample';
import { IfxSearchBarExample } from './generated/IfxSearchBarExample';
import { IfxSearchFieldExample } from './generated/IfxSearchFieldExample';
import { IfxSegmentedControlExample } from './generated/IfxSegmentedControlExample';
import { IfxSelectExample } from './generated/IfxSelectExample';
import { IfxSpinnerExample } from './generated/IfxSpinnerExample';
import { IfxStatusExample } from './generated/IfxStatusExample';
import { IfxStepperExample } from './generated/IfxStepperExample';
import { IfxStepperCompactExample } from './generated/IfxStepperCompactExample';
import { IfxSwitchExample } from './generated/IfxSwitchExample';
import { IfxBasicTableExample } from './generated/IfxBasicTableExample';
import { IfxTableDefaultStateExample } from './generated/IfxTableDefaultStateExample';
import { IfxTabsExample } from './generated/IfxTabsExample';
import { IfxTextFieldExample } from './generated/IfxTextFieldExample';
import { IfxTextareaExample } from './generated/IfxTextareaExample';
import { IfxTooltipExample } from './generated/IfxTooltipExample';
/* </AUTO-GENERATED-IMPORTS> */

import { IfxNavbar, IfxNavbarItem } from "@infineon/infineon-design-system-react";
// Manual examples
import { ModalExample } from "./manual/ModalExample";

function App() {
	const [activeId, setActiveId] = useState<string>(() => {
		const hash = window.location.hash?.slice(1);
		if (hash) return hash;
		
		/* <AUTO-GENERATED-DEFAULT-ID> */
return 'ifx-accordion-example';
		/* </AUTO-GENERATED-DEFAULT-ID> */
	});

	// keep state in sync with URL hash
	useEffect(() => {
		const getHashId = () => window.location.hash?.slice(1);
		// if user opens without a hash, set it to the current activeId (default)
		if (!getHashId()) {
			window.history.replaceState(null, "", `#${activeId}`);
		}

		const onHashChange = () => {
			const next = getHashId();
			if (next) setActiveId(next);
		};

		window.addEventListener("hashchange", onHashChange);
		return () => window.removeEventListener("hashchange", onHashChange);
	}, [activeId]);

	// Highlight code blocks when active example changes
	useEffect(() => {
		Prism.highlightAll();
	}, [activeId]);

	return (
		<>
			<IfxNavbar
				showLogoAndAppname={true}
				applicationName="Infineon Design System - React Example"
				fixed={false}
			>
				<IfxNavbarItem icon="calendar16" slot="left-item">
					All Components
						{/* <AUTO-GENERATED-NAVBAR-ITEMS> */}
<IfxNavbarItem href="#ifx-accordion-example">Accordion</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-action-list-example">Action List</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-alert-example">Alert</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-ai-label-example">AI Label</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-button-example">Button</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-card-example">Card</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-checkbox-example">Checkbox</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-checkbox-group-example">Checkbox Group</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-chip-example">Chip</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-content-switcher-example">Content Switcher</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-date-picker-example">Date Picker</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-dropdown-example">Dropdown</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-footer-example-medium">Footer - Medium</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-icon-button-example">Icon Button</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-indicator-example">Indicator</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-link-example">Link</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-navbar-example">Navigation/Navbar</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-sidebar-example">Navigation/Sidebar</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-notification-example">Notification</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-pagination-example">Pagination</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-progress-bar-example">Progress Bar</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-radio-button-example">Radio Button</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-radio-button-group-example">Radio Button Group</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-search-bar-example">Search Bar</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-search-field-example">Search Field</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-segmented-control-example">Segmented Control</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-select-example">Select/Single Select</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-spinner-example">Spinner</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-status-example">Status</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-stepper-example">Stepper</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-stepper-example-compact">Stepper - Compact</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-switch-example">Switch</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-basic-table-example">Table (basic)</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-table-example-defaultstate">Table (advanced) - DefaultState</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-tabs-example">Tabs</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-text-field-example">Text Field</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-textarea-example">Textarea</IfxNavbarItem>
						<IfxNavbarItem href="#ifx-tooltip-example">Tooltip</IfxNavbarItem>
						{/* </AUTO-GENERATED-NAVBAR-ITEMS> */}
						<IfxNavbarItem href="#ifx-modal-example">Modal</IfxNavbarItem>
				</IfxNavbarItem>
			</IfxNavbar>

			<div className="version-info">
				&#64;infineon/infineon-design-system-react@
				{declaredVersion.includes("workspace") ? "workspace" : installedVersion}
			</div>

			<div className="components">
				{
					/* <AUTO-GENERATED-COMPONENTS> */
<>
					{activeId === "ifx-accordion-example" && (
					  <section id="ifx-accordion-example" className="component-example">
					    <h2>Accordion</h2>
					    <div className="demo">
					      <IfxAccordionExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-action-list-example" && (
					  <section id="ifx-action-list-example" className="component-example">
					    <h2>Action List</h2>
					    <div className="demo">
					      <IfxActionListExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-alert-example" && (
					  <section id="ifx-alert-example" className="component-example">
					    <h2>Alert</h2>
					    <div className="demo">
					      <IfxAlertExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-ai-label-example" && (
					  <section id="ifx-ai-label-example" className="component-example">
					    <h2>AI Label</h2>
					    <div className="demo">
					      <IfxAiLabelExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-button-example" && (
					  <section id="ifx-button-example" className="component-example">
					    <h2>Button</h2>
					    <div className="demo">
					      <IfxButtonExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-card-example" && (
					  <section id="ifx-card-example" className="component-example">
					    <h2>Card</h2>
					    <div className="demo">
					      <IfxCardExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-checkbox-example" && (
					  <section id="ifx-checkbox-example" className="component-example">
					    <h2>Checkbox</h2>
					    <div className="demo">
					      <IfxCheckboxExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-checkbox-group-example" && (
					  <section id="ifx-checkbox-group-example" className="component-example">
					    <h2>Checkbox Group</h2>
					    <div className="demo">
					      <IfxCheckboxGroupExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-chip-example" && (
					  <section id="ifx-chip-example" className="component-example">
					    <h2>Chip</h2>
					    <div className="demo">
					      <IfxChipExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-content-switcher-example" && (
					  <section id="ifx-content-switcher-example" className="component-example">
					    <h2>Content Switcher</h2>
					    <div className="demo">
					      <IfxContentSwitcherExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-date-picker-example" && (
					  <section id="ifx-date-picker-example" className="component-example">
					    <h2>Date Picker</h2>
					    <div className="demo">
					      <IfxDatePickerExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-dropdown-example" && (
					  <section id="ifx-dropdown-example" className="component-example">
					    <h2>Dropdown</h2>
					    <div className="demo">
					      <IfxDropdownExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-footer-example-medium" && (
					  <section id="ifx-footer-example-medium" className="component-example">
					    <h2>Footer - Medium</h2>
					    <div className="demo">
					      <IfxFooterMediumExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-icon-button-example" && (
					  <section id="ifx-icon-button-example" className="component-example">
					    <h2>Icon Button</h2>
					    <div className="demo">
					      <IfxIconButtonExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-indicator-example" && (
					  <section id="ifx-indicator-example" className="component-example">
					    <h2>Indicator</h2>
					    <div className="demo">
					      <IfxIndicatorExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-link-example" && (
					  <section id="ifx-link-example" className="component-example">
					    <h2>Link</h2>
					    <div className="demo">
					      <IfxLinkExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-navbar-example" && (
					  <section id="ifx-navbar-example" className="component-example">
					    <h2>Navigation/Navbar</h2>
					    <div className="demo">
					      <IfxNavbarExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-sidebar-example" && (
					  <section id="ifx-sidebar-example" className="component-example">
					    <h2>Navigation/Sidebar</h2>
					    <div className="demo">
					      <IfxSidebarExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-notification-example" && (
					  <section id="ifx-notification-example" className="component-example">
					    <h2>Notification</h2>
					    <div className="demo">
					      <IfxNotificationExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-pagination-example" && (
					  <section id="ifx-pagination-example" className="component-example">
					    <h2>Pagination</h2>
					    <div className="demo">
					      <IfxPaginationExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-progress-bar-example" && (
					  <section id="ifx-progress-bar-example" className="component-example">
					    <h2>Progress Bar</h2>
					    <div className="demo">
					      <IfxProgressBarExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-radio-button-example" && (
					  <section id="ifx-radio-button-example" className="component-example">
					    <h2>Radio Button</h2>
					    <div className="demo">
					      <IfxRadioButtonExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-radio-button-group-example" && (
					  <section id="ifx-radio-button-group-example" className="component-example">
					    <h2>Radio Button Group</h2>
					    <div className="demo">
					      <IfxRadioButtonGroupExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-search-bar-example" && (
					  <section id="ifx-search-bar-example" className="component-example">
					    <h2>Search Bar</h2>
					    <div className="demo">
					      <IfxSearchBarExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-search-field-example" && (
					  <section id="ifx-search-field-example" className="component-example">
					    <h2>Search Field</h2>
					    <div className="demo">
					      <IfxSearchFieldExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-segmented-control-example" && (
					  <section id="ifx-segmented-control-example" className="component-example">
					    <h2>Segmented Control</h2>
					    <div className="demo">
					      <IfxSegmentedControlExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-select-example" && (
					  <section id="ifx-select-example" className="component-example">
					    <h2>Select/Single Select</h2>
					    <div className="demo">
					      <IfxSelectExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-spinner-example" && (
					  <section id="ifx-spinner-example" className="component-example">
					    <h2>Spinner</h2>
					    <div className="demo">
					      <IfxSpinnerExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-status-example" && (
					  <section id="ifx-status-example" className="component-example">
					    <h2>Status</h2>
					    <div className="demo">
					      <IfxStatusExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-stepper-example" && (
					  <section id="ifx-stepper-example" className="component-example">
					    <h2>Stepper</h2>
					    <div className="demo">
					      <IfxStepperExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-stepper-example-compact" && (
					  <section id="ifx-stepper-example-compact" className="component-example">
					    <h2>Stepper - Compact</h2>
					    <div className="demo">
					      <IfxStepperCompactExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-switch-example" && (
					  <section id="ifx-switch-example" className="component-example">
					    <h2>Switch</h2>
					    <div className="demo">
					      <IfxSwitchExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-basic-table-example" && (
					  <section id="ifx-basic-table-example" className="component-example">
					    <h2>Table (basic)</h2>
					    <div className="demo">
					      <IfxBasicTableExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-table-example-defaultstate" && (
					  <section id="ifx-table-example-defaultstate" className="component-example">
					    <h2>Table (advanced) - DefaultState</h2>
					    <div className="demo">
					      <IfxTableDefaultStateExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-tabs-example" && (
					  <section id="ifx-tabs-example" className="component-example">
					    <h2>Tabs</h2>
					    <div className="demo">
					      <IfxTabsExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-text-field-example" && (
					  <section id="ifx-text-field-example" className="component-example">
					    <h2>Text Field</h2>
					    <div className="demo">
					      <IfxTextFieldExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-textarea-example" && (
					  <section id="ifx-textarea-example" className="component-example">
					    <h2>Textarea</h2>
					    <div className="demo">
					      <IfxTextareaExample />
					    </div>
					  </section>
					)}

					{activeId === "ifx-tooltip-example" && (
					  <section id="ifx-tooltip-example" className="component-example">
					    <h2>Tooltip</h2>
					    <div className="demo">
					      <IfxTooltipExample />
					    </div>
					  </section>
					)}
					</>
					/* </AUTO-GENERATED-COMPONENTS> */
				}

				{/* Manual examples that require custom logic */}
				{activeId === "ifx-modal-example" && (
					<section id="ifx-modal-example" className="component-example">
						<h2>Modal (Manual Example)</h2>
						<div className="demo">
							<ModalExample />
						</div>
					</section>
				)}
			</div>
		</>
	);
}

export default App;
