import "./App.css";
import "prismjs/themes/prism.css";
import Prism from "prismjs";
import { useEffect } from "react";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-tsx";

// @ts-expect-error
import packageJson from "../package.json";

const declaredVersion = (packageJson.dependencies as Record<string, string>)[
	"@infineon/infineon-design-system-react"
];

import { version as installedVersion } from "@infineon/infineon-design-system-react/package.json";

/* <AUTO-GENERATED-IMPORTS> */
import { IfxAccordionExample } from './generated/IfxAccordionExample';
import { IfxActionListExample } from './generated/IfxActionListExample';
import { IfxAlertExample } from './generated/IfxAlertExample';
import { IfxAiLabelExample } from './generated/IfxAiLabelExample';
import { IfxButtonExample } from './generated/IfxButtonExample';
import { IfxCardExample } from './generated/IfxCardExample';
import { IfxCheckboxExample } from './generated/IfxCheckboxExample';
import { IfxCheckboxGroupExample } from './generated/IfxCheckboxGroupExample';
import { IfxChipExample } from './generated/IfxChipExample';
import { IfxContentSwitcherExample } from './generated/IfxContentSwitcherExample';
import { IfxDatePickerExample } from './generated/IfxDatePickerExample';
import { IfxDropdownExample } from './generated/IfxDropdownExample';
import { IfxFooterMediumExample } from './generated/IfxFooterMediumExample';
import { IfxIconButtonExample } from './generated/IfxIconButtonExample';
import { IfxIndicatorExample } from './generated/IfxIndicatorExample';
import { IfxLinkExample } from './generated/IfxLinkExample';
import { IfxNavbarExample } from './generated/IfxNavbarExample';
import { IfxSidebarExample } from './generated/IfxSidebarExample';
import { IfxNotificationExample } from './generated/IfxNotificationExample';
import { IfxPaginationExample } from './generated/IfxPaginationExample';
import { IfxProgressBarExample } from './generated/IfxProgressBarExample';
import { IfxRadioButtonExample } from './generated/IfxRadioButtonExample';
import { IfxRadioButtonGroupExample } from './generated/IfxRadioButtonGroupExample';
import { IfxSearchBarExample } from './generated/IfxSearchBarExample';
import { IfxSearchFieldExample } from './generated/IfxSearchFieldExample';
import { IfxSegmentedControlExample } from './generated/IfxSegmentedControlExample';
import { IfxSelectExample } from './generated/IfxSelectExample';
import { IfxSpinnerExample } from './generated/IfxSpinnerExample';
import { IfxStatusExample } from './generated/IfxStatusExample';
import { IfxStepperExample } from './generated/IfxStepperExample';
import { IfxStepperCompactExample } from './generated/IfxStepperCompactExample';
import { IfxSwitchExample } from './generated/IfxSwitchExample';
import { IfxBasicTableExample } from './generated/IfxBasicTableExample';
import { IfxTableDefaultStateExample } from './generated/IfxTableDefaultStateExample';
import { IfxTabsExample } from './generated/IfxTabsExample';
import { IfxTextFieldExample } from './generated/IfxTextFieldExample';
import { IfxTextareaExample } from './generated/IfxTextareaExample';
import { IfxTooltipExample } from './generated/IfxTooltipExample';
/* </AUTO-GENERATED-IMPORTS> */

import { IfxNavbar } from "@infineon/infineon-design-system-react";
// Manual examples
import { ModalExample } from "./manual/ModalExample";

function App() {
	// Highlight code blocks on mount and updates
	useEffect(() => {
		Prism.highlightAll();
	});

	return (
		<>
			<IfxNavbar
				showLogoAndAppname={true}
				applicationName="Infineon Design System - React Example"
				fixed={false}
			/>

			<div className="version-info">
				&#64;infineon/infineon-design-system-react@
				{declaredVersion.includes("workspace") ? "workspace" : installedVersion}
			</div>

			<div className="components">
				{
					/* <AUTO-GENERATED-COMPONENTS> */
<>
					<section id="ifx-accordion-example" className="component-example">
					  <h2>Accordion</h2>
					  <div className="demo">
					    <IfxAccordionExample />
					  </div>
					</section>

					<section id="ifx-action-list-example" className="component-example">
					  <h2>Action List</h2>
					  <div className="demo">
					    <IfxActionListExample />
					  </div>
					</section>

					<section id="ifx-alert-example" className="component-example">
					  <h2>Alert</h2>
					  <div className="demo">
					    <IfxAlertExample />
					  </div>
					</section>

					<section id="ifx-ai-label-example" className="component-example">
					  <h2>AI Label</h2>
					  <div className="demo">
					    <IfxAiLabelExample />
					  </div>
					</section>

					<section id="ifx-button-example" className="component-example">
					  <h2>Button</h2>
					  <div className="demo">
					    <IfxButtonExample />
					  </div>
					</section>

					<section id="ifx-card-example" className="component-example">
					  <h2>Card</h2>
					  <div className="demo">
					    <IfxCardExample />
					  </div>
					</section>

					<section id="ifx-checkbox-example" className="component-example">
					  <h2>Checkbox</h2>
					  <div className="demo">
					    <IfxCheckboxExample />
					  </div>
					</section>

					<section id="ifx-checkbox-group-example" className="component-example">
					  <h2>Checkbox Group</h2>
					  <div className="demo">
					    <IfxCheckboxGroupExample />
					  </div>
					</section>

					<section id="ifx-chip-example" className="component-example">
					  <h2>Chip</h2>
					  <div className="demo">
					    <IfxChipExample />
					  </div>
					</section>

					<section id="ifx-content-switcher-example" className="component-example">
					  <h2>Content Switcher</h2>
					  <div className="demo">
					    <IfxContentSwitcherExample />
					  </div>
					</section>

					<section id="ifx-date-picker-example" className="component-example">
					  <h2>Date Picker</h2>
					  <div className="demo">
					    <IfxDatePickerExample />
					  </div>
					</section>

					<section id="ifx-dropdown-example" className="component-example">
					  <h2>Dropdown</h2>
					  <div className="demo">
					    <IfxDropdownExample />
					  </div>
					</section>

					<section id="ifx-footer-example-medium" className="component-example">
					  <h2>Footer - Medium</h2>
					  <div className="demo">
					    <IfxFooterMediumExample />
					  </div>
					</section>

					<section id="ifx-icon-button-example" className="component-example">
					  <h2>Icon Button</h2>
					  <div className="demo">
					    <IfxIconButtonExample />
					  </div>
					</section>

					<section id="ifx-indicator-example" className="component-example">
					  <h2>Indicator</h2>
					  <div className="demo">
					    <IfxIndicatorExample />
					  </div>
					</section>

					<section id="ifx-link-example" className="component-example">
					  <h2>Link</h2>
					  <div className="demo">
					    <IfxLinkExample />
					  </div>
					</section>

					<section id="ifx-navbar-example" className="component-example">
					  <h2>Navigation/Navbar</h2>
					  <div className="demo">
					    <IfxNavbarExample />
					  </div>
					</section>

					<section id="ifx-sidebar-example" className="component-example">
					  <h2>Navigation/Sidebar</h2>
					  <div className="demo">
					    <IfxSidebarExample />
					  </div>
					</section>

					<section id="ifx-notification-example" className="component-example">
					  <h2>Notification</h2>
					  <div className="demo">
					    <IfxNotificationExample />
					  </div>
					</section>

					<section id="ifx-pagination-example" className="component-example">
					  <h2>Pagination</h2>
					  <div className="demo">
					    <IfxPaginationExample />
					  </div>
					</section>

					<section id="ifx-progress-bar-example" className="component-example">
					  <h2>Progress Bar</h2>
					  <div className="demo">
					    <IfxProgressBarExample />
					  </div>
					</section>

					<section id="ifx-radio-button-example" className="component-example">
					  <h2>Radio Button</h2>
					  <div className="demo">
					    <IfxRadioButtonExample />
					  </div>
					</section>

					<section id="ifx-radio-button-group-example" className="component-example">
					  <h2>Radio Button Group</h2>
					  <div className="demo">
					    <IfxRadioButtonGroupExample />
					  </div>
					</section>

					<section id="ifx-search-bar-example" className="component-example">
					  <h2>Search Bar</h2>
					  <div className="demo">
					    <IfxSearchBarExample />
					  </div>
					</section>

					<section id="ifx-search-field-example" className="component-example">
					  <h2>Search Field</h2>
					  <div className="demo">
					    <IfxSearchFieldExample />
					  </div>
					</section>

					<section id="ifx-segmented-control-example" className="component-example">
					  <h2>Segmented Control</h2>
					  <div className="demo">
					    <IfxSegmentedControlExample />
					  </div>
					</section>

					<section id="ifx-select-example" className="component-example">
					  <h2>Select/Single Select</h2>
					  <div className="demo">
					    <IfxSelectExample />
					  </div>
					</section>

					<section id="ifx-spinner-example" className="component-example">
					  <h2>Spinner</h2>
					  <div className="demo">
					    <IfxSpinnerExample />
					  </div>
					</section>

					<section id="ifx-status-example" className="component-example">
					  <h2>Status</h2>
					  <div className="demo">
					    <IfxStatusExample />
					  </div>
					</section>

					<section id="ifx-stepper-example" className="component-example">
					  <h2>Stepper</h2>
					  <div className="demo">
					    <IfxStepperExample />
					  </div>
					</section>

					<section id="ifx-stepper-example-compact" className="component-example">
					  <h2>Stepper - Compact</h2>
					  <div className="demo">
					    <IfxStepperCompactExample />
					  </div>
					</section>

					<section id="ifx-switch-example" className="component-example">
					  <h2>Switch</h2>
					  <div className="demo">
					    <IfxSwitchExample />
					  </div>
					</section>

					<section id="ifx-basic-table-example" className="component-example">
					  <h2>Table (basic)</h2>
					  <div className="demo">
					    <IfxBasicTableExample />
					  </div>
					</section>

					<section id="ifx-table-example-defaultstate" className="component-example">
					  <h2>Table (advanced) - DefaultState</h2>
					  <div className="demo">
					    <IfxTableDefaultStateExample />
					  </div>
					</section>

					<section id="ifx-tabs-example" className="component-example">
					  <h2>Tabs</h2>
					  <div className="demo">
					    <IfxTabsExample />
					  </div>
					</section>

					<section id="ifx-text-field-example" className="component-example">
					  <h2>Text Field</h2>
					  <div className="demo">
					    <IfxTextFieldExample />
					  </div>
					</section>

					<section id="ifx-textarea-example" className="component-example">
					  <h2>Textarea</h2>
					  <div className="demo">
					    <IfxTextareaExample />
					  </div>
					</section>

					<section id="ifx-tooltip-example" className="component-example">
					  <h2>Tooltip</h2>
					  <div className="demo">
					    <IfxTooltipExample />
					  </div>
					</section>
					</>
					/* </AUTO-GENERATED-COMPONENTS> */
				}

				{/* Manual examples that require custom logic */}
				<section id="modal-example" className="component-example">
					<h2>Modal (Manual Example)</h2>
					<div className="demo">
						<ModalExample />
					</div>
				</section>
			</div>
		</>
	);
}

export default App;
