import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=15432%3A6691",
  {
    props: {
      captionText: figma.string("Caption Text"),
      labelText: figma.string("Label Text"),
      optionalIndicator: figma.boolean("Optional Indicator"),
      required: figma.boolean("Required Indicator"),
      dragAndDrop: figma.enum("Variant", {
        "Dropzone": true
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      }),
      error: figma.enum("State", {
        "Error": true,
      }),
    },
    example: (props) => html`<ifx-file-upload
      drag-and-drop=${props.dragAndDrop}
      label=${props.labelText}
      max-file-size-m-b="7" 
      max-files="1"
      allowed-file-types="jpg,jpeg,png,pdf"
      allow-any-filetype="false"
      label-required-error="You must upload at least one file."
      label-browse-files="Browse files"
      label-drag-and-drop="Drag &amp; Drop or browse files to upload"
      label-uploaded-files-heading="Uploaded files"
      label-file-too-large="Upload failed. Max file size: {{size}}MB."
      label-unsupported-file-type="Unsupported file type."
      label-uploaded="Successfully uploaded"
      label-supported-formats-template="Supported file formats: {{types}}. Max file size: {{size}}MB."
      label-file-singular="file" 
      label-file-plural="files" 
      label-max-files-info="You can upload up to {{count}} {{files}}."
      label-max-files-exceeded="You have exceeded the maximum of {{count}} {{files}}."
      label-upload-failed="Upload failed. Please try again."
      error=${props.error}
      disabled=${props.disabled}
      required=${props.required}
    >
    </ifx-file-upload>`,
  },
)