import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=80406%3A147",
  {
    props: {
      label: figma.string("Status Text"),
      color: figma.enum("Color", {
        Green: "green-500",
        Orange: "orange-500",
        Ocean: "ocean-500",
        Red: "red-500",
        Berry: "berry-500",
        Gray: "engineering-500",
        "Gray Light": "engineering-300",
      }),
      border: figma.enum("Style", {
        Simple: false,
        "With Outline": true,
      }),
    },
    example: (props) => html`
      <ifx-status
        label=${props.label}
        color=${props.color}
        border=${props.border}
      ></ifx-status>
    `,
  },
)
