name: 'Check Package Availability'
description: 'Wait for npm packages to become available with exponential backoff'
inputs:
  packages:
    description: 'Comma-separated list of NPM package names (e.g., @infineon/infineon-design-system-stencil,@infineon/infineon-design-system-react)'
    required: true
  version:
    description: 'Package version to check for'
    required: true
  max-attempts:
    description: 'Maximum number of attempts to check'
    required: false
    default: '10'
  max-delay:
    description: 'Maximum delay between attempts in seconds'
    required: false
    default: '20'
  registry:
    description: 'NPM registry URL'
    required: false
    default: 'https://registry.npmjs.org'
outputs:
  available:
    description: 'Whether the package is available (true/false)'
    value: ${{ steps.check.outputs.available }}
  attempts:
    description: 'Number of attempts made'
    value: ${{ steps.check.outputs.attempts }}
runs:
  using: 'composite'
  steps:
    - name: Check package availability
      id: check
      shell: bash
      run: |
        PACKAGES="${{ inputs.packages }}"
        VERSION="${{ inputs.version }}"
        MAX_ATTEMPTS="${{ inputs.max-attempts }}"
        MAX_DELAY="${{ inputs.max-delay }}"
        REGISTRY="${{ inputs.registry }}"
        
        # Convert comma-separated string to array
        IFS=',' read -ra PACKAGE_ARRAY <<< "$PACKAGES"
        
        # Function to check a single package
        check_package() {
          local package=$1
          npm view "$package@$VERSION" version --registry="$REGISTRY" &>/dev/null
        }
        
        echo "⏳ Waiting for packages to be available..."
        echo "Packages: $PACKAGES"
        echo "Version: $VERSION"
        echo "Registry: $REGISTRY"
        echo "Max attempts: $MAX_ATTEMPTS"
        echo "Max delay: $MAX_DELAY seconds"
        echo ""
        
        ALL_AVAILABLE="false"
        for i in $(seq 1 $MAX_ATTEMPTS); do
          echo "Attempt $i/$MAX_ATTEMPTS..."
          
          MISSING_PACKAGES=()
          ALL_FOUND=true
          
          for package in "${PACKAGE_ARRAY[@]}"; do
            package=$(echo "$package" | xargs) # trim whitespace
            if check_package "$package"; then
              echo "  ✅ $package@$VERSION - available"
            else
              echo "  ❌ $package@$VERSION - not available"
              MISSING_PACKAGES+=("$package")
              ALL_FOUND=false
            fi
          done
          
          if [ "$ALL_FOUND" = true ]; then
            echo ""
            echo "✅ All packages available after $i attempt(s)!"
            ALL_AVAILABLE="true"
            break
          fi
          
          if [ $i -lt $MAX_ATTEMPTS ]; then
            DELAY=$((2**i < MAX_DELAY ? 2**i : MAX_DELAY))
            echo ""
            echo "⏳ Missing ${#MISSING_PACKAGES[@]} package(s), waiting ${DELAY} seconds before next attempt..."
            echo ""
            sleep $DELAY
          fi
        done
        
        if [ "$ALL_AVAILABLE" = "false" ]; then
          echo ""
          echo "❌ Not all packages available after $MAX_ATTEMPTS attempts"
          echo "Missing packages:"
          for package in "${MISSING_PACKAGES[@]}"; do
            echo "  - $package@$VERSION"
          done
          exit 1
        fi
        
        echo "available=$ALL_AVAILABLE" >> $GITHUB_OUTPUT
        echo "attempts=$i" >> $GITHUB_OUTPUT