/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IfxAlert {
        /**
          * @default 'assertive'
         */
        "AriaLive": string;
        /**
          * @default true
         */
        "closable": boolean;
        "icon": string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'success' | 'danger' | 'warning' | 'info';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface IfxAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIfxAlertElement;
}
declare global {
    interface HTMLIfxAlertElementEventMap {
        "ifxClose": any;
    }
    interface HTMLIfxAlertElement extends Components.IfxAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIfxAlertElementEventMap>(type: K, listener: (this: HTMLIfxAlertElement, ev: IfxAlertCustomEvent<HTMLIfxAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIfxAlertElementEventMap>(type: K, listener: (this: HTMLIfxAlertElement, ev: IfxAlertCustomEvent<HTMLIfxAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIfxAlertElement: {
        prototype: HTMLIfxAlertElement;
        new (): HTMLIfxAlertElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ifx-alert": HTMLIfxAlertElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IfxAlert {
        /**
          * @default 'assertive'
         */
        "AriaLive"?: string;
        /**
          * @default true
         */
        "closable"?: boolean;
        "icon"?: string;
        "onIfxClose"?: (event: IfxAlertCustomEvent<any>) => void;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'success' | 'danger' | 'warning' | 'info';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ifx-alert": IfxAlert;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ifx-alert": LocalJSX.IfxAlert & JSXBase.HTMLAttributes<HTMLIfxAlertElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
