const DiagnosticCode = {
	TARGET_PROP_ALREADY_EXISTS: "DDS001",
	INVALID_MANIFEST: "DDS005",
	PARSE_FAILED: "DDS007",
	OVERLAPPING_EDITS: "DDS008",
	UNSUPPORTED_ANGULAR_BINDING: "DDS010",
	DYNAMIC_INLINE_TEMPLATE_UNSUPPORTED: "DDS011",
};

module.exports = {
	DiagnosticCode,
};
