'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChangeEvent, type ChipItemSelectEvent, type IfxBreadcrumbItemLabelCustomEvent, type IfxChipCustomEvent, type IfxChipItemCustomEvent, type IfxContentSwitcherCustomEvent, type IfxDropdownMenuCustomEvent, type IfxSearchFieldCustomEvent, type IfxSelectCustomEvent, type IfxTextFieldCustomEvent } from "@infineon/infineon-design-system-stencil";
import { IfxAccordionItem as IfxAccordionItemElement, defineCustomElement as defineIfxAccordionItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-accordion-item.js";
import { IfxAccordion as IfxAccordionElement, defineCustomElement as defineIfxAccordion } from "@infineon/infineon-design-system-stencil/dist/components/ifx-accordion.js";
import { IfxAlert as IfxAlertElement, defineCustomElement as defineIfxAlert } from "@infineon/infineon-design-system-stencil/dist/components/ifx-alert.js";
import { IfxBadge as IfxBadgeElement, defineCustomElement as defineIfxBadge } from "@infineon/infineon-design-system-stencil/dist/components/ifx-badge.js";
import { IfxBasicTable as IfxBasicTableElement, defineCustomElement as defineIfxBasicTable } from "@infineon/infineon-design-system-stencil/dist/components/ifx-basic-table.js";
import { IfxBreadcrumbItemLabel as IfxBreadcrumbItemLabelElement, defineCustomElement as defineIfxBreadcrumbItemLabel } from "@infineon/infineon-design-system-stencil/dist/components/ifx-breadcrumb-item-label.js";
import { IfxBreadcrumbItem as IfxBreadcrumbItemElement, defineCustomElement as defineIfxBreadcrumbItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-breadcrumb-item.js";
import { IfxBreadcrumb as IfxBreadcrumbElement, defineCustomElement as defineIfxBreadcrumb } from "@infineon/infineon-design-system-stencil/dist/components/ifx-breadcrumb.js";
import { IfxButton as IfxButtonElement, defineCustomElement as defineIfxButton } from "@infineon/infineon-design-system-stencil/dist/components/ifx-button.js";
import { IfxCardHeadline as IfxCardHeadlineElement, defineCustomElement as defineIfxCardHeadline } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card-headline.js";
import { IfxCardImage as IfxCardImageElement, defineCustomElement as defineIfxCardImage } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card-image.js";
import { IfxCardLinks as IfxCardLinksElement, defineCustomElement as defineIfxCardLinks } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card-links.js";
import { IfxCardOverline as IfxCardOverlineElement, defineCustomElement as defineIfxCardOverline } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card-overline.js";
import { IfxCardText as IfxCardTextElement, defineCustomElement as defineIfxCardText } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card-text.js";
import { IfxCard as IfxCardElement, defineCustomElement as defineIfxCard } from "@infineon/infineon-design-system-stencil/dist/components/ifx-card.js";
import { IfxCheckbox as IfxCheckboxElement, defineCustomElement as defineIfxCheckbox } from "@infineon/infineon-design-system-stencil/dist/components/ifx-checkbox.js";
import { IfxChipItem as IfxChipItemElement, defineCustomElement as defineIfxChipItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-chip-item.js";
import { IfxChip as IfxChipElement, defineCustomElement as defineIfxChip } from "@infineon/infineon-design-system-stencil/dist/components/ifx-chip.js";
import { IfxContentSwitcherItem as IfxContentSwitcherItemElement, defineCustomElement as defineIfxContentSwitcherItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-content-switcher-item.js";
import { IfxContentSwitcher as IfxContentSwitcherElement, defineCustomElement as defineIfxContentSwitcher } from "@infineon/infineon-design-system-stencil/dist/components/ifx-content-switcher.js";
import { IfxDatePicker as IfxDatePickerElement, defineCustomElement as defineIfxDatePicker } from "@infineon/infineon-design-system-stencil/dist/components/ifx-date-picker.js";
import { IfxDropdownHeader as IfxDropdownHeaderElement, defineCustomElement as defineIfxDropdownHeader } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-header.js";
import { IfxDropdownItem as IfxDropdownItemElement, defineCustomElement as defineIfxDropdownItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-item.js";
import { IfxDropdownMenu as IfxDropdownMenuElement, defineCustomElement as defineIfxDropdownMenu } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-menu.js";
import { IfxDropdownSeparator as IfxDropdownSeparatorElement, defineCustomElement as defineIfxDropdownSeparator } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-separator.js";
import { IfxDropdownTriggerButton as IfxDropdownTriggerButtonElement, defineCustomElement as defineIfxDropdownTriggerButton } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-trigger-button.js";
import { IfxDropdownTrigger as IfxDropdownTriggerElement, defineCustomElement as defineIfxDropdownTrigger } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown-trigger.js";
import { IfxDropdown as IfxDropdownElement, defineCustomElement as defineIfxDropdown } from "@infineon/infineon-design-system-stencil/dist/components/ifx-dropdown.js";
import { IfxFaq as IfxFaqElement, defineCustomElement as defineIfxFaq } from "@infineon/infineon-design-system-stencil/dist/components/ifx-faq.js";
import { IfxFilterAccordion as IfxFilterAccordionElement, defineCustomElement as defineIfxFilterAccordion } from "@infineon/infineon-design-system-stencil/dist/components/ifx-filter-accordion.js";
import { IfxFilterBar as IfxFilterBarElement, defineCustomElement as defineIfxFilterBar } from "@infineon/infineon-design-system-stencil/dist/components/ifx-filter-bar.js";
import { IfxFilterSearch as IfxFilterSearchElement, defineCustomElement as defineIfxFilterSearch } from "@infineon/infineon-design-system-stencil/dist/components/ifx-filter-search.js";
import { IfxFilterTypeGroup as IfxFilterTypeGroupElement, defineCustomElement as defineIfxFilterTypeGroup } from "@infineon/infineon-design-system-stencil/dist/components/ifx-filter-type-group.js";
import { IfxFooterColumn as IfxFooterColumnElement, defineCustomElement as defineIfxFooterColumn } from "@infineon/infineon-design-system-stencil/dist/components/ifx-footer-column.js";
import { IfxFooter as IfxFooterElement, defineCustomElement as defineIfxFooter } from "@infineon/infineon-design-system-stencil/dist/components/ifx-footer.js";
import { IfxIconButton as IfxIconButtonElement, defineCustomElement as defineIfxIconButton } from "@infineon/infineon-design-system-stencil/dist/components/ifx-icon-button.js";
import { IfxIcon as IfxIconElement, defineCustomElement as defineIfxIcon } from "@infineon/infineon-design-system-stencil/dist/components/ifx-icon.js";
import { IfxIconsPreview as IfxIconsPreviewElement, defineCustomElement as defineIfxIconsPreview } from "@infineon/infineon-design-system-stencil/dist/components/ifx-icons-preview.js";
import { IfxLink as IfxLinkElement, defineCustomElement as defineIfxLink } from "@infineon/infineon-design-system-stencil/dist/components/ifx-link.js";
import { IfxListEntry as IfxListEntryElement, defineCustomElement as defineIfxListEntry } from "@infineon/infineon-design-system-stencil/dist/components/ifx-list-entry.js";
import { IfxListGroup as IfxListGroupElement, defineCustomElement as defineIfxListGroup } from "@infineon/infineon-design-system-stencil/dist/components/ifx-list-group.js";
import { IfxListItem as IfxListItemElement, defineCustomElement as defineIfxListItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-list-item.js";
import { IfxListNotification as IfxListNotificationElement, defineCustomElement as defineIfxListNotification } from "@infineon/infineon-design-system-stencil/dist/components/ifx-list-notification.js";
import { IfxList as IfxListElement, defineCustomElement as defineIfxList } from "@infineon/infineon-design-system-stencil/dist/components/ifx-list.js";
import { IfxModal as IfxModalElement, defineCustomElement as defineIfxModal } from "@infineon/infineon-design-system-stencil/dist/components/ifx-modal.js";
import { IfxMultiselect as IfxMultiselectElement, defineCustomElement as defineIfxMultiselect } from "@infineon/infineon-design-system-stencil/dist/components/ifx-multiselect.js";
import { IfxNavbarItem as IfxNavbarItemElement, defineCustomElement as defineIfxNavbarItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-navbar-item.js";
import { IfxNavbarProfile as IfxNavbarProfileElement, defineCustomElement as defineIfxNavbarProfile } from "@infineon/infineon-design-system-stencil/dist/components/ifx-navbar-profile.js";
import { IfxNavbar as IfxNavbarElement, defineCustomElement as defineIfxNavbar } from "@infineon/infineon-design-system-stencil/dist/components/ifx-navbar.js";
import { IfxNotification as IfxNotificationElement, defineCustomElement as defineIfxNotification } from "@infineon/infineon-design-system-stencil/dist/components/ifx-notification.js";
import { IfxNumberIndicator as IfxNumberIndicatorElement, defineCustomElement as defineIfxNumberIndicator } from "@infineon/infineon-design-system-stencil/dist/components/ifx-number-indicator.js";
import { IfxOverviewTable as IfxOverviewTableElement, defineCustomElement as defineIfxOverviewTable } from "@infineon/infineon-design-system-stencil/dist/components/ifx-overview-table.js";
import { IfxPagination as IfxPaginationElement, defineCustomElement as defineIfxPagination } from "@infineon/infineon-design-system-stencil/dist/components/ifx-pagination.js";
import { IfxProgressBar as IfxProgressBarElement, defineCustomElement as defineIfxProgressBar } from "@infineon/infineon-design-system-stencil/dist/components/ifx-progress-bar.js";
import { IfxRadioButton as IfxRadioButtonElement, defineCustomElement as defineIfxRadioButton } from "@infineon/infineon-design-system-stencil/dist/components/ifx-radio-button.js";
import { IfxSearchBar as IfxSearchBarElement, defineCustomElement as defineIfxSearchBar } from "@infineon/infineon-design-system-stencil/dist/components/ifx-search-bar.js";
import { IfxSearchField as IfxSearchFieldElement, defineCustomElement as defineIfxSearchField } from "@infineon/infineon-design-system-stencil/dist/components/ifx-search-field.js";
import { IfxSelect as IfxSelectElement, defineCustomElement as defineIfxSelect } from "@infineon/infineon-design-system-stencil/dist/components/ifx-select.js";
import { IfxSetFilter as IfxSetFilterElement, defineCustomElement as defineIfxSetFilter } from "@infineon/infineon-design-system-stencil/dist/components/ifx-set-filter.js";
import { IfxSidebarItem as IfxSidebarItemElement, defineCustomElement as defineIfxSidebarItem } from "@infineon/infineon-design-system-stencil/dist/components/ifx-sidebar-item.js";
import { IfxSidebarTitle as IfxSidebarTitleElement, defineCustomElement as defineIfxSidebarTitle } from "@infineon/infineon-design-system-stencil/dist/components/ifx-sidebar-title.js";
import { IfxSidebar as IfxSidebarElement, defineCustomElement as defineIfxSidebar } from "@infineon/infineon-design-system-stencil/dist/components/ifx-sidebar.js";
import { IfxSlider as IfxSliderElement, defineCustomElement as defineIfxSlider } from "@infineon/infineon-design-system-stencil/dist/components/ifx-slider.js";
import { IfxSpinner as IfxSpinnerElement, defineCustomElement as defineIfxSpinner } from "@infineon/infineon-design-system-stencil/dist/components/ifx-spinner.js";
import { IfxStatus as IfxStatusElement, defineCustomElement as defineIfxStatus } from "@infineon/infineon-design-system-stencil/dist/components/ifx-status.js";
import { IfxStep as IfxStepElement, defineCustomElement as defineIfxStep } from "@infineon/infineon-design-system-stencil/dist/components/ifx-step.js";
import { IfxStepper as IfxStepperElement, defineCustomElement as defineIfxStepper } from "@infineon/infineon-design-system-stencil/dist/components/ifx-stepper.js";
import { IfxSwitch as IfxSwitchElement, defineCustomElement as defineIfxSwitch } from "@infineon/infineon-design-system-stencil/dist/components/ifx-switch.js";
import { IfxTab as IfxTabElement, defineCustomElement as defineIfxTab } from "@infineon/infineon-design-system-stencil/dist/components/ifx-tab.js";
import { IfxTable as IfxTableElement, defineCustomElement as defineIfxTable } from "@infineon/infineon-design-system-stencil/dist/components/ifx-table.js";
import { IfxTabs as IfxTabsElement, defineCustomElement as defineIfxTabs } from "@infineon/infineon-design-system-stencil/dist/components/ifx-tabs.js";
import { IfxTag as IfxTagElement, defineCustomElement as defineIfxTag } from "@infineon/infineon-design-system-stencil/dist/components/ifx-tag.js";
import { IfxTextField as IfxTextFieldElement, defineCustomElement as defineIfxTextField } from "@infineon/infineon-design-system-stencil/dist/components/ifx-text-field.js";
import { IfxTooltip as IfxTooltipElement, defineCustomElement as defineIfxTooltip } from "@infineon/infineon-design-system-stencil/dist/components/ifx-tooltip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IfxAccordionEvents = NonNullable<unknown>;

export const IfxAccordion: StencilReactComponent<IfxAccordionElement, IfxAccordionEvents> = /*@__PURE__*/ createComponent<IfxAccordionElement, IfxAccordionEvents>({
    tagName: 'ifx-accordion',
    elementClass: IfxAccordionElement,
    react: React,
    events: {} as IfxAccordionEvents,
    defineCustomElement: defineIfxAccordion
});

type IfxAccordionItemEvents = {
    onIfxItemOpen: EventName<CustomEvent<any>>,
    onIfxItemClose: EventName<CustomEvent<any>>
};

export const IfxAccordionItem: StencilReactComponent<IfxAccordionItemElement, IfxAccordionItemEvents> = /*@__PURE__*/ createComponent<IfxAccordionItemElement, IfxAccordionItemEvents>({
    tagName: 'ifx-accordion-item',
    elementClass: IfxAccordionItemElement,
    react: React,
    events: {
        onIfxItemOpen: 'ifxItemOpen',
        onIfxItemClose: 'ifxItemClose'
    } as IfxAccordionItemEvents,
    defineCustomElement: defineIfxAccordionItem
});

type IfxAlertEvents = { onIfxClose: EventName<CustomEvent<any>> };

export const IfxAlert: StencilReactComponent<IfxAlertElement, IfxAlertEvents> = /*@__PURE__*/ createComponent<IfxAlertElement, IfxAlertEvents>({
    tagName: 'ifx-alert',
    elementClass: IfxAlertElement,
    react: React,
    events: { onIfxClose: 'ifxClose' } as IfxAlertEvents,
    defineCustomElement: defineIfxAlert
});

type IfxBadgeEvents = NonNullable<unknown>;

export const IfxBadge: StencilReactComponent<IfxBadgeElement, IfxBadgeEvents> = /*@__PURE__*/ createComponent<IfxBadgeElement, IfxBadgeEvents>({
    tagName: 'ifx-badge',
    elementClass: IfxBadgeElement,
    react: React,
    events: {} as IfxBadgeEvents,
    defineCustomElement: defineIfxBadge
});

type IfxBasicTableEvents = NonNullable<unknown>;

export const IfxBasicTable: StencilReactComponent<IfxBasicTableElement, IfxBasicTableEvents> = /*@__PURE__*/ createComponent<IfxBasicTableElement, IfxBasicTableEvents>({
    tagName: 'ifx-basic-table',
    elementClass: IfxBasicTableElement,
    react: React,
    events: {} as IfxBasicTableEvents,
    defineCustomElement: defineIfxBasicTable
});

type IfxBreadcrumbEvents = NonNullable<unknown>;

export const IfxBreadcrumb: StencilReactComponent<IfxBreadcrumbElement, IfxBreadcrumbEvents> = /*@__PURE__*/ createComponent<IfxBreadcrumbElement, IfxBreadcrumbEvents>({
    tagName: 'ifx-breadcrumb',
    elementClass: IfxBreadcrumbElement,
    react: React,
    events: {} as IfxBreadcrumbEvents,
    defineCustomElement: defineIfxBreadcrumb
});

type IfxBreadcrumbItemEvents = NonNullable<unknown>;

export const IfxBreadcrumbItem: StencilReactComponent<IfxBreadcrumbItemElement, IfxBreadcrumbItemEvents> = /*@__PURE__*/ createComponent<IfxBreadcrumbItemElement, IfxBreadcrumbItemEvents>({
    tagName: 'ifx-breadcrumb-item',
    elementClass: IfxBreadcrumbItemElement,
    react: React,
    events: {} as IfxBreadcrumbItemEvents,
    defineCustomElement: defineIfxBreadcrumbItem
});

type IfxBreadcrumbItemLabelEvents = { onBreadcrumbMenuIconWrapper: EventName<IfxBreadcrumbItemLabelCustomEvent<CustomEvent>> };

export const IfxBreadcrumbItemLabel: StencilReactComponent<IfxBreadcrumbItemLabelElement, IfxBreadcrumbItemLabelEvents> = /*@__PURE__*/ createComponent<IfxBreadcrumbItemLabelElement, IfxBreadcrumbItemLabelEvents>({
    tagName: 'ifx-breadcrumb-item-label',
    elementClass: IfxBreadcrumbItemLabelElement,
    react: React,
    events: { onBreadcrumbMenuIconWrapper: 'breadcrumbMenuIconWrapper' } as IfxBreadcrumbItemLabelEvents,
    defineCustomElement: defineIfxBreadcrumbItemLabel
});

type IfxButtonEvents = NonNullable<unknown>;

export const IfxButton: StencilReactComponent<IfxButtonElement, IfxButtonEvents> = /*@__PURE__*/ createComponent<IfxButtonElement, IfxButtonEvents>({
    tagName: 'ifx-button',
    elementClass: IfxButtonElement,
    react: React,
    events: {} as IfxButtonEvents,
    defineCustomElement: defineIfxButton
});

type IfxCardEvents = NonNullable<unknown>;

export const IfxCard: StencilReactComponent<IfxCardElement, IfxCardEvents> = /*@__PURE__*/ createComponent<IfxCardElement, IfxCardEvents>({
    tagName: 'ifx-card',
    elementClass: IfxCardElement,
    react: React,
    events: {} as IfxCardEvents,
    defineCustomElement: defineIfxCard
});

type IfxCardHeadlineEvents = NonNullable<unknown>;

export const IfxCardHeadline: StencilReactComponent<IfxCardHeadlineElement, IfxCardHeadlineEvents> = /*@__PURE__*/ createComponent<IfxCardHeadlineElement, IfxCardHeadlineEvents>({
    tagName: 'ifx-card-headline',
    elementClass: IfxCardHeadlineElement,
    react: React,
    events: {} as IfxCardHeadlineEvents,
    defineCustomElement: defineIfxCardHeadline
});

type IfxCardImageEvents = { onImgPosition: EventName<CustomEvent<any>> };

export const IfxCardImage: StencilReactComponent<IfxCardImageElement, IfxCardImageEvents> = /*@__PURE__*/ createComponent<IfxCardImageElement, IfxCardImageEvents>({
    tagName: 'ifx-card-image',
    elementClass: IfxCardImageElement,
    react: React,
    events: { onImgPosition: 'imgPosition' } as IfxCardImageEvents,
    defineCustomElement: defineIfxCardImage
});

type IfxCardLinksEvents = NonNullable<unknown>;

export const IfxCardLinks: StencilReactComponent<IfxCardLinksElement, IfxCardLinksEvents> = /*@__PURE__*/ createComponent<IfxCardLinksElement, IfxCardLinksEvents>({
    tagName: 'ifx-card-links',
    elementClass: IfxCardLinksElement,
    react: React,
    events: {} as IfxCardLinksEvents,
    defineCustomElement: defineIfxCardLinks
});

type IfxCardOverlineEvents = NonNullable<unknown>;

export const IfxCardOverline: StencilReactComponent<IfxCardOverlineElement, IfxCardOverlineEvents> = /*@__PURE__*/ createComponent<IfxCardOverlineElement, IfxCardOverlineEvents>({
    tagName: 'ifx-card-overline',
    elementClass: IfxCardOverlineElement,
    react: React,
    events: {} as IfxCardOverlineEvents,
    defineCustomElement: defineIfxCardOverline
});

type IfxCardTextEvents = NonNullable<unknown>;

export const IfxCardText: StencilReactComponent<IfxCardTextElement, IfxCardTextEvents> = /*@__PURE__*/ createComponent<IfxCardTextElement, IfxCardTextEvents>({
    tagName: 'ifx-card-text',
    elementClass: IfxCardTextElement,
    react: React,
    events: {} as IfxCardTextEvents,
    defineCustomElement: defineIfxCardText
});

type IfxCheckboxEvents = { onIfxChange: EventName<CustomEvent<any>> };

export const IfxCheckbox: StencilReactComponent<IfxCheckboxElement, IfxCheckboxEvents> = /*@__PURE__*/ createComponent<IfxCheckboxElement, IfxCheckboxEvents>({
    tagName: 'ifx-checkbox',
    elementClass: IfxCheckboxElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxCheckboxEvents,
    defineCustomElement: defineIfxCheckbox
});

type IfxChipEvents = { onIfxChipChange: EventName<IfxChipCustomEvent<{ previousSelection: Array<ChipItemSelectEvent>, currentSelection: Array<ChipItemSelectEvent>, name: string }>> };

export const IfxChip: StencilReactComponent<IfxChipElement, IfxChipEvents> = /*@__PURE__*/ createComponent<IfxChipElement, IfxChipEvents>({
    tagName: 'ifx-chip',
    elementClass: IfxChipElement,
    react: React,
    events: { onIfxChipChange: 'ifxChipChange' } as IfxChipEvents,
    defineCustomElement: defineIfxChip
});

type IfxChipItemEvents = { onIfxChipItemSelect: EventName<IfxChipItemCustomEvent<ChipItemSelectEvent>> };

export const IfxChipItem: StencilReactComponent<IfxChipItemElement, IfxChipItemEvents> = /*@__PURE__*/ createComponent<IfxChipItemElement, IfxChipItemEvents>({
    tagName: 'ifx-chip-item',
    elementClass: IfxChipItemElement,
    react: React,
    events: { onIfxChipItemSelect: 'ifxChipItemSelect' } as IfxChipItemEvents,
    defineCustomElement: defineIfxChipItem
});

type IfxContentSwitcherEvents = { onIfxChange: EventName<IfxContentSwitcherCustomEvent<ChangeEvent>> };

export const IfxContentSwitcher: StencilReactComponent<IfxContentSwitcherElement, IfxContentSwitcherEvents> = /*@__PURE__*/ createComponent<IfxContentSwitcherElement, IfxContentSwitcherEvents>({
    tagName: 'ifx-content-switcher',
    elementClass: IfxContentSwitcherElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxContentSwitcherEvents,
    defineCustomElement: defineIfxContentSwitcher
});

type IfxContentSwitcherItemEvents = NonNullable<unknown>;

export const IfxContentSwitcherItem: StencilReactComponent<IfxContentSwitcherItemElement, IfxContentSwitcherItemEvents> = /*@__PURE__*/ createComponent<IfxContentSwitcherItemElement, IfxContentSwitcherItemEvents>({
    tagName: 'ifx-content-switcher-item',
    elementClass: IfxContentSwitcherItemElement,
    react: React,
    events: {} as IfxContentSwitcherItemEvents,
    defineCustomElement: defineIfxContentSwitcherItem
});

type IfxDatePickerEvents = { onIfxDate: EventName<CustomEvent<any>> };

export const IfxDatePicker: StencilReactComponent<IfxDatePickerElement, IfxDatePickerEvents> = /*@__PURE__*/ createComponent<IfxDatePickerElement, IfxDatePickerEvents>({
    tagName: 'ifx-date-picker',
    elementClass: IfxDatePickerElement,
    react: React,
    events: { onIfxDate: 'ifxDate' } as IfxDatePickerEvents,
    defineCustomElement: defineIfxDatePicker
});

type IfxDropdownEvents = {
    onIfxOpen: EventName<CustomEvent<any>>,
    onIfxClose: EventName<CustomEvent<any>>,
    onIfxDropdown: EventName<CustomEvent<any>>
};

export const IfxDropdown: StencilReactComponent<IfxDropdownElement, IfxDropdownEvents> = /*@__PURE__*/ createComponent<IfxDropdownElement, IfxDropdownEvents>({
    tagName: 'ifx-dropdown',
    elementClass: IfxDropdownElement,
    react: React,
    events: {
        onIfxOpen: 'ifxOpen',
        onIfxClose: 'ifxClose',
        onIfxDropdown: 'ifxDropdown'
    } as IfxDropdownEvents,
    defineCustomElement: defineIfxDropdown
});

type IfxDropdownHeaderEvents = NonNullable<unknown>;

export const IfxDropdownHeader: StencilReactComponent<IfxDropdownHeaderElement, IfxDropdownHeaderEvents> = /*@__PURE__*/ createComponent<IfxDropdownHeaderElement, IfxDropdownHeaderEvents>({
    tagName: 'ifx-dropdown-header',
    elementClass: IfxDropdownHeaderElement,
    react: React,
    events: {} as IfxDropdownHeaderEvents,
    defineCustomElement: defineIfxDropdownHeader
});

type IfxDropdownItemEvents = { onIfxDropdownItem: EventName<CustomEvent<any>> };

export const IfxDropdownItem: StencilReactComponent<IfxDropdownItemElement, IfxDropdownItemEvents> = /*@__PURE__*/ createComponent<IfxDropdownItemElement, IfxDropdownItemEvents>({
    tagName: 'ifx-dropdown-item',
    elementClass: IfxDropdownItemElement,
    react: React,
    events: { onIfxDropdownItem: 'ifxDropdownItem' } as IfxDropdownItemEvents,
    defineCustomElement: defineIfxDropdownItem
});

type IfxDropdownMenuEvents = {
    onMenuSize: EventName<CustomEvent<any>>,
    onIfxDropdownMenuItem: EventName<IfxDropdownMenuCustomEvent<CustomEvent>>
};

export const IfxDropdownMenu: StencilReactComponent<IfxDropdownMenuElement, IfxDropdownMenuEvents> = /*@__PURE__*/ createComponent<IfxDropdownMenuElement, IfxDropdownMenuEvents>({
    tagName: 'ifx-dropdown-menu',
    elementClass: IfxDropdownMenuElement,
    react: React,
    events: {
        onMenuSize: 'menuSize',
        onIfxDropdownMenuItem: 'ifxDropdownMenuItem'
    } as IfxDropdownMenuEvents,
    defineCustomElement: defineIfxDropdownMenu
});

type IfxDropdownSeparatorEvents = NonNullable<unknown>;

export const IfxDropdownSeparator: StencilReactComponent<IfxDropdownSeparatorElement, IfxDropdownSeparatorEvents> = /*@__PURE__*/ createComponent<IfxDropdownSeparatorElement, IfxDropdownSeparatorEvents>({
    tagName: 'ifx-dropdown-separator',
    elementClass: IfxDropdownSeparatorElement,
    react: React,
    events: {} as IfxDropdownSeparatorEvents,
    defineCustomElement: defineIfxDropdownSeparator
});

type IfxDropdownTriggerEvents = NonNullable<unknown>;

export const IfxDropdownTrigger: StencilReactComponent<IfxDropdownTriggerElement, IfxDropdownTriggerEvents> = /*@__PURE__*/ createComponent<IfxDropdownTriggerElement, IfxDropdownTriggerEvents>({
    tagName: 'ifx-dropdown-trigger',
    elementClass: IfxDropdownTriggerElement,
    react: React,
    events: {} as IfxDropdownTriggerEvents,
    defineCustomElement: defineIfxDropdownTrigger
});

type IfxDropdownTriggerButtonEvents = NonNullable<unknown>;

export const IfxDropdownTriggerButton: StencilReactComponent<IfxDropdownTriggerButtonElement, IfxDropdownTriggerButtonEvents> = /*@__PURE__*/ createComponent<IfxDropdownTriggerButtonElement, IfxDropdownTriggerButtonEvents>({
    tagName: 'ifx-dropdown-trigger-button',
    elementClass: IfxDropdownTriggerButtonElement,
    react: React,
    events: {} as IfxDropdownTriggerButtonEvents,
    defineCustomElement: defineIfxDropdownTriggerButton
});

type IfxFaqEvents = NonNullable<unknown>;

export const IfxFaq: StencilReactComponent<IfxFaqElement, IfxFaqEvents> = /*@__PURE__*/ createComponent<IfxFaqElement, IfxFaqEvents>({
    tagName: 'ifx-faq',
    elementClass: IfxFaqElement,
    react: React,
    events: {} as IfxFaqEvents,
    defineCustomElement: defineIfxFaq
});

type IfxFilterAccordionEvents = { onIfxFilterAccordionChange: EventName<CustomEvent<any>> };

export const IfxFilterAccordion: StencilReactComponent<IfxFilterAccordionElement, IfxFilterAccordionEvents> = /*@__PURE__*/ createComponent<IfxFilterAccordionElement, IfxFilterAccordionEvents>({
    tagName: 'ifx-filter-accordion',
    elementClass: IfxFilterAccordionElement,
    react: React,
    events: { onIfxFilterAccordionChange: 'ifxFilterAccordionChange' } as IfxFilterAccordionEvents,
    defineCustomElement: defineIfxFilterAccordion
});

type IfxFilterBarEvents = { onIfxTopbarFilterChange: EventName<CustomEvent<any>> };

export const IfxFilterBar: StencilReactComponent<IfxFilterBarElement, IfxFilterBarEvents> = /*@__PURE__*/ createComponent<IfxFilterBarElement, IfxFilterBarEvents>({
    tagName: 'ifx-filter-bar',
    elementClass: IfxFilterBarElement,
    react: React,
    events: { onIfxTopbarFilterChange: 'ifxTopbarFilterChange' } as IfxFilterBarEvents,
    defineCustomElement: defineIfxFilterBar
});

type IfxFilterSearchEvents = { onIfxFilterSearchChange: EventName<CustomEvent<any>> };

export const IfxFilterSearch: StencilReactComponent<IfxFilterSearchElement, IfxFilterSearchEvents> = /*@__PURE__*/ createComponent<IfxFilterSearchElement, IfxFilterSearchEvents>({
    tagName: 'ifx-filter-search',
    elementClass: IfxFilterSearchElement,
    react: React,
    events: { onIfxFilterSearchChange: 'ifxFilterSearchChange' } as IfxFilterSearchEvents,
    defineCustomElement: defineIfxFilterSearch
});

type IfxFilterTypeGroupEvents = { onIfxSidebarFilterChange: EventName<CustomEvent<any>> };

export const IfxFilterTypeGroup: StencilReactComponent<IfxFilterTypeGroupElement, IfxFilterTypeGroupEvents> = /*@__PURE__*/ createComponent<IfxFilterTypeGroupElement, IfxFilterTypeGroupEvents>({
    tagName: 'ifx-filter-type-group',
    elementClass: IfxFilterTypeGroupElement,
    react: React,
    events: { onIfxSidebarFilterChange: 'ifxSidebarFilterChange' } as IfxFilterTypeGroupEvents,
    defineCustomElement: defineIfxFilterTypeGroup
});

type IfxFooterEvents = NonNullable<unknown>;

export const IfxFooter: StencilReactComponent<IfxFooterElement, IfxFooterEvents> = /*@__PURE__*/ createComponent<IfxFooterElement, IfxFooterEvents>({
    tagName: 'ifx-footer',
    elementClass: IfxFooterElement,
    react: React,
    events: {} as IfxFooterEvents,
    defineCustomElement: defineIfxFooter
});

type IfxFooterColumnEvents = NonNullable<unknown>;

export const IfxFooterColumn: StencilReactComponent<IfxFooterColumnElement, IfxFooterColumnEvents> = /*@__PURE__*/ createComponent<IfxFooterColumnElement, IfxFooterColumnEvents>({
    tagName: 'ifx-footer-column',
    elementClass: IfxFooterColumnElement,
    react: React,
    events: {} as IfxFooterColumnEvents,
    defineCustomElement: defineIfxFooterColumn
});

type IfxIconEvents = { onConsoleError: EventName<CustomEvent<boolean>> };

export const IfxIcon: StencilReactComponent<IfxIconElement, IfxIconEvents> = /*@__PURE__*/ createComponent<IfxIconElement, IfxIconEvents>({
    tagName: 'ifx-icon',
    elementClass: IfxIconElement,
    react: React,
    events: { onConsoleError: 'consoleError' } as IfxIconEvents,
    defineCustomElement: defineIfxIcon
});

type IfxIconButtonEvents = NonNullable<unknown>;

export const IfxIconButton: StencilReactComponent<IfxIconButtonElement, IfxIconButtonEvents> = /*@__PURE__*/ createComponent<IfxIconButtonElement, IfxIconButtonEvents>({
    tagName: 'ifx-icon-button',
    elementClass: IfxIconButtonElement,
    react: React,
    events: {} as IfxIconButtonEvents,
    defineCustomElement: defineIfxIconButton
});

type IfxIconsPreviewEvents = NonNullable<unknown>;

export const IfxIconsPreview: StencilReactComponent<IfxIconsPreviewElement, IfxIconsPreviewEvents> = /*@__PURE__*/ createComponent<IfxIconsPreviewElement, IfxIconsPreviewEvents>({
    tagName: 'ifx-icons-preview',
    elementClass: IfxIconsPreviewElement,
    react: React,
    events: {} as IfxIconsPreviewEvents,
    defineCustomElement: defineIfxIconsPreview
});

type IfxLinkEvents = NonNullable<unknown>;

export const IfxLink: StencilReactComponent<IfxLinkElement, IfxLinkEvents> = /*@__PURE__*/ createComponent<IfxLinkElement, IfxLinkEvents>({
    tagName: 'ifx-link',
    elementClass: IfxLinkElement,
    react: React,
    events: {} as IfxLinkEvents,
    defineCustomElement: defineIfxLink
});

type IfxListEvents = { onIfxListUpdate: EventName<CustomEvent<any>> };

export const IfxList: StencilReactComponent<IfxListElement, IfxListEvents> = /*@__PURE__*/ createComponent<IfxListElement, IfxListEvents>({
    tagName: 'ifx-list',
    elementClass: IfxListElement,
    react: React,
    events: { onIfxListUpdate: 'ifxListUpdate' } as IfxListEvents,
    defineCustomElement: defineIfxList
});

type IfxListEntryEvents = { onIfxListEntryChange: EventName<CustomEvent<any>> };

export const IfxListEntry: StencilReactComponent<IfxListEntryElement, IfxListEntryEvents> = /*@__PURE__*/ createComponent<IfxListEntryElement, IfxListEntryEvents>({
    tagName: 'ifx-list-entry',
    elementClass: IfxListEntryElement,
    react: React,
    events: { onIfxListEntryChange: 'ifxListEntryChange' } as IfxListEntryEvents,
    defineCustomElement: defineIfxListEntry
});

type IfxListGroupEvents = NonNullable<unknown>;

export const IfxListGroup: StencilReactComponent<IfxListGroupElement, IfxListGroupEvents> = /*@__PURE__*/ createComponent<IfxListGroupElement, IfxListGroupEvents>({
    tagName: 'ifx-list-group',
    elementClass: IfxListGroupElement,
    react: React,
    events: {} as IfxListGroupEvents,
    defineCustomElement: defineIfxListGroup
});

type IfxListItemEvents = NonNullable<unknown>;

export const IfxListItem: StencilReactComponent<IfxListItemElement, IfxListItemEvents> = /*@__PURE__*/ createComponent<IfxListItemElement, IfxListItemEvents>({
    tagName: 'ifx-list-item',
    elementClass: IfxListItemElement,
    react: React,
    events: {} as IfxListItemEvents,
    defineCustomElement: defineIfxListItem
});

type IfxListNotificationEvents = NonNullable<unknown>;

export const IfxListNotification: StencilReactComponent<IfxListNotificationElement, IfxListNotificationEvents> = /*@__PURE__*/ createComponent<IfxListNotificationElement, IfxListNotificationEvents>({
    tagName: 'ifx-list-notification',
    elementClass: IfxListNotificationElement,
    react: React,
    events: {} as IfxListNotificationEvents,
    defineCustomElement: defineIfxListNotification
});

type IfxModalEvents = {
    onIfxModalOpen: EventName<CustomEvent<any>>,
    onIfxModalClose: EventName<CustomEvent<any>>
};

export const IfxModal: StencilReactComponent<IfxModalElement, IfxModalEvents> = /*@__PURE__*/ createComponent<IfxModalElement, IfxModalEvents>({
    tagName: 'ifx-modal',
    elementClass: IfxModalElement,
    react: React,
    events: {
        onIfxModalOpen: 'ifxModalOpen',
        onIfxModalClose: 'ifxModalClose'
    } as IfxModalEvents,
    defineCustomElement: defineIfxModal
});

type IfxMultiselectEvents = {
    onIfxSelect: EventName<CustomEvent<any>>,
    onIfxMultiselectIsOpen: EventName<CustomEvent<any>>
};

export const IfxMultiselect: StencilReactComponent<IfxMultiselectElement, IfxMultiselectEvents> = /*@__PURE__*/ createComponent<IfxMultiselectElement, IfxMultiselectEvents>({
    tagName: 'ifx-multiselect',
    elementClass: IfxMultiselectElement,
    react: React,
    events: {
        onIfxSelect: 'ifxSelect',
        onIfxMultiselectIsOpen: 'ifxMultiselectIsOpen'
    } as IfxMultiselectEvents,
    defineCustomElement: defineIfxMultiselect
});

type IfxNavbarEvents = { onIfxNavbarMobileMenuIsOpen: EventName<CustomEvent<any>> };

export const IfxNavbar: StencilReactComponent<IfxNavbarElement, IfxNavbarEvents> = /*@__PURE__*/ createComponent<IfxNavbarElement, IfxNavbarEvents>({
    tagName: 'ifx-navbar',
    elementClass: IfxNavbarElement,
    react: React,
    events: { onIfxNavbarMobileMenuIsOpen: 'ifxNavbarMobileMenuIsOpen' } as IfxNavbarEvents,
    defineCustomElement: defineIfxNavbar
});

type IfxNavbarItemEvents = { onIfxNavItem: EventName<CustomEvent<any>> };

export const IfxNavbarItem: StencilReactComponent<IfxNavbarItemElement, IfxNavbarItemEvents> = /*@__PURE__*/ createComponent<IfxNavbarItemElement, IfxNavbarItemEvents>({
    tagName: 'ifx-navbar-item',
    elementClass: IfxNavbarItemElement,
    react: React,
    events: { onIfxNavItem: 'ifxNavItem' } as IfxNavbarItemEvents,
    defineCustomElement: defineIfxNavbarItem
});

type IfxNavbarProfileEvents = NonNullable<unknown>;

export const IfxNavbarProfile: StencilReactComponent<IfxNavbarProfileElement, IfxNavbarProfileEvents> = /*@__PURE__*/ createComponent<IfxNavbarProfileElement, IfxNavbarProfileEvents>({
    tagName: 'ifx-navbar-profile',
    elementClass: IfxNavbarProfileElement,
    react: React,
    events: {} as IfxNavbarProfileEvents,
    defineCustomElement: defineIfxNavbarProfile
});

type IfxNotificationEvents = NonNullable<unknown>;

export const IfxNotification: StencilReactComponent<IfxNotificationElement, IfxNotificationEvents> = /*@__PURE__*/ createComponent<IfxNotificationElement, IfxNotificationEvents>({
    tagName: 'ifx-notification',
    elementClass: IfxNotificationElement,
    react: React,
    events: {} as IfxNotificationEvents,
    defineCustomElement: defineIfxNotification
});

type IfxNumberIndicatorEvents = NonNullable<unknown>;

export const IfxNumberIndicator: StencilReactComponent<IfxNumberIndicatorElement, IfxNumberIndicatorEvents> = /*@__PURE__*/ createComponent<IfxNumberIndicatorElement, IfxNumberIndicatorEvents>({
    tagName: 'ifx-number-indicator',
    elementClass: IfxNumberIndicatorElement,
    react: React,
    events: {} as IfxNumberIndicatorEvents,
    defineCustomElement: defineIfxNumberIndicator
});

type IfxOverviewTableEvents = NonNullable<unknown>;

export const IfxOverviewTable: StencilReactComponent<IfxOverviewTableElement, IfxOverviewTableEvents> = /*@__PURE__*/ createComponent<IfxOverviewTableElement, IfxOverviewTableEvents>({
    tagName: 'ifx-overview-table',
    elementClass: IfxOverviewTableElement,
    react: React,
    events: {} as IfxOverviewTableEvents,
    defineCustomElement: defineIfxOverviewTable
});

type IfxPaginationEvents = {
    onIfxPageChange: EventName<CustomEvent<any>>,
    onIfxNextPage: EventName<CustomEvent<any>>,
    onIfxPrevPage: EventName<CustomEvent<any>>
};

export const IfxPagination: StencilReactComponent<IfxPaginationElement, IfxPaginationEvents> = /*@__PURE__*/ createComponent<IfxPaginationElement, IfxPaginationEvents>({
    tagName: 'ifx-pagination',
    elementClass: IfxPaginationElement,
    react: React,
    events: {
        onIfxPageChange: 'ifxPageChange',
        onIfxNextPage: 'ifxNextPage',
        onIfxPrevPage: 'ifxPrevPage'
    } as IfxPaginationEvents,
    defineCustomElement: defineIfxPagination
});

type IfxProgressBarEvents = NonNullable<unknown>;

export const IfxProgressBar: StencilReactComponent<IfxProgressBarElement, IfxProgressBarEvents> = /*@__PURE__*/ createComponent<IfxProgressBarElement, IfxProgressBarEvents>({
    tagName: 'ifx-progress-bar',
    elementClass: IfxProgressBarElement,
    react: React,
    events: {} as IfxProgressBarEvents,
    defineCustomElement: defineIfxProgressBar
});

type IfxRadioButtonEvents = { onIfxChange: EventName<CustomEvent<any>> };

export const IfxRadioButton: StencilReactComponent<IfxRadioButtonElement, IfxRadioButtonEvents> = /*@__PURE__*/ createComponent<IfxRadioButtonElement, IfxRadioButtonEvents>({
    tagName: 'ifx-radio-button',
    elementClass: IfxRadioButtonElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxRadioButtonEvents,
    defineCustomElement: defineIfxRadioButton
});

type IfxSearchBarEvents = {
    onIfxInput: EventName<CustomEvent<any>>,
    onIfxSearchBarIsOpen: EventName<CustomEvent<any>>
};

export const IfxSearchBar: StencilReactComponent<IfxSearchBarElement, IfxSearchBarEvents> = /*@__PURE__*/ createComponent<IfxSearchBarElement, IfxSearchBarEvents>({
    tagName: 'ifx-search-bar',
    elementClass: IfxSearchBarElement,
    react: React,
    events: {
        onIfxInput: 'ifxInput',
        onIfxSearchBarIsOpen: 'ifxSearchBarIsOpen'
    } as IfxSearchBarEvents,
    defineCustomElement: defineIfxSearchBar
});

type IfxSearchFieldEvents = { onIfxInput: EventName<IfxSearchFieldCustomEvent<String>> };

export const IfxSearchField: StencilReactComponent<IfxSearchFieldElement, IfxSearchFieldEvents> = /*@__PURE__*/ createComponent<IfxSearchFieldElement, IfxSearchFieldEvents>({
    tagName: 'ifx-search-field',
    elementClass: IfxSearchFieldElement,
    react: React,
    events: { onIfxInput: 'ifxInput' } as IfxSearchFieldEvents,
    defineCustomElement: defineIfxSearchField
});

type IfxSelectEvents = {
    onIfxSelect: EventName<IfxSelectCustomEvent<CustomEvent>>,
    onIfxInput: EventName<IfxSelectCustomEvent<CustomEvent>>
};

export const IfxSelect: StencilReactComponent<IfxSelectElement, IfxSelectEvents> = /*@__PURE__*/ createComponent<IfxSelectElement, IfxSelectEvents>({
    tagName: 'ifx-select',
    elementClass: IfxSelectElement,
    react: React,
    events: {
        onIfxSelect: 'ifxSelect',
        onIfxInput: 'ifxInput'
    } as IfxSelectEvents,
    defineCustomElement: defineIfxSelect
});

type IfxSetFilterEvents = { onIfxFilterSelect: EventName<CustomEvent<any>> };

export const IfxSetFilter: StencilReactComponent<IfxSetFilterElement, IfxSetFilterEvents> = /*@__PURE__*/ createComponent<IfxSetFilterElement, IfxSetFilterEvents>({
    tagName: 'ifx-set-filter',
    elementClass: IfxSetFilterElement,
    react: React,
    events: { onIfxFilterSelect: 'ifxFilterSelect' } as IfxSetFilterEvents,
    defineCustomElement: defineIfxSetFilter
});

type IfxSidebarEvents = NonNullable<unknown>;

export const IfxSidebar: StencilReactComponent<IfxSidebarElement, IfxSidebarEvents> = /*@__PURE__*/ createComponent<IfxSidebarElement, IfxSidebarEvents>({
    tagName: 'ifx-sidebar',
    elementClass: IfxSidebarElement,
    react: React,
    events: {} as IfxSidebarEvents,
    defineCustomElement: defineIfxSidebar
});

type IfxSidebarItemEvents = {
    onIfxSidebarMenu: EventName<CustomEvent<any>>,
    onIfxSidebarNavigationItem: EventName<CustomEvent<any>>,
    onIfxSidebarActionItem: EventName<CustomEvent<any>>
};

export const IfxSidebarItem: StencilReactComponent<IfxSidebarItemElement, IfxSidebarItemEvents> = /*@__PURE__*/ createComponent<IfxSidebarItemElement, IfxSidebarItemEvents>({
    tagName: 'ifx-sidebar-item',
    elementClass: IfxSidebarItemElement,
    react: React,
    events: {
        onIfxSidebarMenu: 'ifxSidebarMenu',
        onIfxSidebarNavigationItem: 'ifxSidebarNavigationItem',
        onIfxSidebarActionItem: 'ifxSidebarActionItem'
    } as IfxSidebarItemEvents,
    defineCustomElement: defineIfxSidebarItem
});

type IfxSidebarTitleEvents = NonNullable<unknown>;

export const IfxSidebarTitle: StencilReactComponent<IfxSidebarTitleElement, IfxSidebarTitleEvents> = /*@__PURE__*/ createComponent<IfxSidebarTitleElement, IfxSidebarTitleEvents>({
    tagName: 'ifx-sidebar-title',
    elementClass: IfxSidebarTitleElement,
    react: React,
    events: {} as IfxSidebarTitleEvents,
    defineCustomElement: defineIfxSidebarTitle
});

type IfxSliderEvents = { onIfxChange: EventName<CustomEvent<any>> };

export const IfxSlider: StencilReactComponent<IfxSliderElement, IfxSliderEvents> = /*@__PURE__*/ createComponent<IfxSliderElement, IfxSliderEvents>({
    tagName: 'ifx-slider',
    elementClass: IfxSliderElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxSliderEvents,
    defineCustomElement: defineIfxSlider
});

type IfxSpinnerEvents = NonNullable<unknown>;

export const IfxSpinner: StencilReactComponent<IfxSpinnerElement, IfxSpinnerEvents> = /*@__PURE__*/ createComponent<IfxSpinnerElement, IfxSpinnerEvents>({
    tagName: 'ifx-spinner',
    elementClass: IfxSpinnerElement,
    react: React,
    events: {} as IfxSpinnerEvents,
    defineCustomElement: defineIfxSpinner
});

type IfxStatusEvents = NonNullable<unknown>;

export const IfxStatus: StencilReactComponent<IfxStatusElement, IfxStatusEvents> = /*@__PURE__*/ createComponent<IfxStatusElement, IfxStatusEvents>({
    tagName: 'ifx-status',
    elementClass: IfxStatusElement,
    react: React,
    events: {} as IfxStatusEvents,
    defineCustomElement: defineIfxStatus
});

type IfxStepEvents = NonNullable<unknown>;

export const IfxStep: StencilReactComponent<IfxStepElement, IfxStepEvents> = /*@__PURE__*/ createComponent<IfxStepElement, IfxStepEvents>({
    tagName: 'ifx-step',
    elementClass: IfxStepElement,
    react: React,
    events: {} as IfxStepEvents,
    defineCustomElement: defineIfxStep
});

type IfxStepperEvents = { onIfxChange: EventName<CustomEvent<any>> };

export const IfxStepper: StencilReactComponent<IfxStepperElement, IfxStepperEvents> = /*@__PURE__*/ createComponent<IfxStepperElement, IfxStepperEvents>({
    tagName: 'ifx-stepper',
    elementClass: IfxStepperElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxStepperEvents,
    defineCustomElement: defineIfxStepper
});

type IfxSwitchEvents = { onIfxChange: EventName<CustomEvent<boolean>> };

export const IfxSwitch: StencilReactComponent<IfxSwitchElement, IfxSwitchEvents> = /*@__PURE__*/ createComponent<IfxSwitchElement, IfxSwitchEvents>({
    tagName: 'ifx-switch',
    elementClass: IfxSwitchElement,
    react: React,
    events: { onIfxChange: 'ifxChange' } as IfxSwitchEvents,
    defineCustomElement: defineIfxSwitch
});

type IfxTabEvents = NonNullable<unknown>;

export const IfxTab: StencilReactComponent<IfxTabElement, IfxTabEvents> = /*@__PURE__*/ createComponent<IfxTabElement, IfxTabEvents>({
    tagName: 'ifx-tab',
    elementClass: IfxTabElement,
    react: React,
    events: {} as IfxTabEvents,
    defineCustomElement: defineIfxTab
});

type IfxTableEvents = NonNullable<unknown>;

export const IfxTable: StencilReactComponent<IfxTableElement, IfxTableEvents> = /*@__PURE__*/ createComponent<IfxTableElement, IfxTableEvents>({
    tagName: 'ifx-table',
    elementClass: IfxTableElement,
    react: React,
    events: {} as IfxTableEvents,
    defineCustomElement: defineIfxTable
});

type IfxTabsEvents = { onIfxTabChange: EventName<CustomEvent<any>> };

export const IfxTabs: StencilReactComponent<IfxTabsElement, IfxTabsEvents> = /*@__PURE__*/ createComponent<IfxTabsElement, IfxTabsEvents>({
    tagName: 'ifx-tabs',
    elementClass: IfxTabsElement,
    react: React,
    events: { onIfxTabChange: 'ifxTabChange' } as IfxTabsEvents,
    defineCustomElement: defineIfxTabs
});

type IfxTagEvents = NonNullable<unknown>;

export const IfxTag: StencilReactComponent<IfxTagElement, IfxTagEvents> = /*@__PURE__*/ createComponent<IfxTagElement, IfxTagEvents>({
    tagName: 'ifx-tag',
    elementClass: IfxTagElement,
    react: React,
    events: {} as IfxTagEvents,
    defineCustomElement: defineIfxTag
});

type IfxTextFieldEvents = { onIfxInput: EventName<IfxTextFieldCustomEvent<String>> };

export const IfxTextField: StencilReactComponent<IfxTextFieldElement, IfxTextFieldEvents> = /*@__PURE__*/ createComponent<IfxTextFieldElement, IfxTextFieldEvents>({
    tagName: 'ifx-text-field',
    elementClass: IfxTextFieldElement,
    react: React,
    events: { onIfxInput: 'ifxInput' } as IfxTextFieldEvents,
    defineCustomElement: defineIfxTextField
});

type IfxTooltipEvents = NonNullable<unknown>;

export const IfxTooltip: StencilReactComponent<IfxTooltipElement, IfxTooltipEvents> = /*@__PURE__*/ createComponent<IfxTooltipElement, IfxTooltipEvents>({
    tagName: 'ifx-tooltip',
    elementClass: IfxTooltipElement,
    react: React,
    events: {} as IfxTooltipEvents,
    defineCustomElement: defineIfxTooltip
});
