import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=63857%3A4335",
  {
    props: {
      "caption": figma.nestedProps('Caption', {
          "text": figma.string('Caption text'),
      }),
      "label": figma.boolean('Show Label', {
        true: figma.nestedProps('Labels', {
          "text": figma.string('Label text'),
        }),
        false: { "text": undefined }
      }),
      "required": figma.nestedProps('Labels', {
        "required": figma.enum('Variant', {
          'Required': true,
        }),
      }),
      size: figma.enum("Size", {
        Small: "small",
        Regular: "regular",
      }),
      children: figma.children("_Segmented Control States"),
    },
    example: (props) => html`<ifx-segmented-control label=${props.label.text} caption=${props.caption.text} size=${props.size} required=${props.required.required}>
      ${props.children}
    </ifx-segmented-control>
      `,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// _Segmented Control States
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=63797%3A3276",
  {
    props: {
      label: figma.boolean("Show Label", {
        true: figma.string("Label Text"),
        false: undefined,
      }),
      selected: figma.enum("State", {
        Selected: true
      }),
    },
    example: (props) => html`<ifx-segment icon="star16" selected=${props.selected}>${props.label}</ifx-segment>`,
  },
)
