name: Report a bug
description: Report a bug or an error
title: "Component-name: short summary"
labels: 
  - bug
  - request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! 🐛
        
        **💡 Want to contribute?** We welcome pull requests! If you're interested in fixing this bug yourself, please check our [Contributing Guidelines](https://github.com/Infineon/infineon-design-system-stencil/blob/master/CONTRIBUTING.md) to get started.
  - type: textarea
    attributes:
      label: Detailed description of how to reproduce the problem
      description: A clear and concise description of what the bug is, and how to reproduce is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Upload a screenshot
      description: Please provide a screenshot of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the development framework
      description: Tech stack, environment, versions, and any other relevant information to help us reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true  
  - type: textarea
    attributes:
      label: Additional information
      description: Free text