name: New component request
description: Request a new component
title: "New Component: component-name"
labels: 
  - enhancement
  - request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your component request! 🎨
        
        **💡 Want to contribute?** Building new components is a great way to contribute! Our [Contributing Guidelines](https://github.com/Infineon/infineon-design-system-stencil/blob/master/CONTRIBUTING.md) will guide you through the component development process.
  - type: textarea
    attributes:
      label: Detailed description of the component, its design and behavior
      description: A clear and concise description of the component
    validations:
      required: true
  - type: textarea
    attributes:
      label: Do you plan to use this component for web applications, mobile or both?
      description: Free text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Upload a screenshot or reference an example if possible
      description: If you are able to illustrate the component with an example, please provide a sample reference or a screenshot.
  - type: textarea
    attributes:
      label: Why do you need this component?
      description: Describe the context and use case.
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Do you have a deadline?
      description: Give us a sense of how urgent this component is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What project is this component for?
      description: Describe the technology stack and the project's purpose.
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Additional information
      description: Free text