name: DDS Developer Feature / Task
description: Describe a new feature or technical task to be implemented by DDS Developers
title: "Component name: short summary"
labels:
  - enhancement
  - request
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a short, clear summary of the feature or technical task.
      placeholder: e.g. "Add loading state to Button component."
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background / Context
      description: Describe the background of this request. Why is it needed? What problem are we solving?
      placeholder: |
        e.g. "Users need feedback when clicking the button, so a loading state is required to indicate progress."

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria / Definition of Done
      description: List the specific conditions that must be met for this task to be considered complete.
      options:
        - label: Clearly defined behavior or output is implemented
        - label: Matches the design and UX specifications
        - label: Semantic HTML is used appropriately
        - label: Sufficient custom events are emitted on changes/interactions with the component
        - label: Add Storybook view with controls
        - label: Fully covered by automated tests (unit/integration)
        - label: Meets accessibility requirements (Keyboarybord navigation, ARIA roles, etc.)
        - label: Test components in the example wrapper (Angular, React, Vanilla JS and Vue)
        - label: Reviewed and merged into the main branch

  - type: textarea
    id: task_checklist
    attributes:
      label: Task Checklist
      description: Break down the work into atomic developer tasks. These should be implementation-focused.
      placeholder: |
        - [ ] Add loading state prop to Button component
        - [ ] Implement loading spinner in Button
        - [ ] Add unit custom event for loading state
        - [ ] Add Storybook example for loading state
        - [] …

        > Note: Please use the actual GitHub task checklist (checkbox list) in the issue so progress can be tracked.

        > If a task is large or complex, consider creating a separate issue for it and reference it here.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Include links to relevant specs, designs, documentation, or related issues.
      placeholder: |
        - [Figma Design Spec](url)
        - [Component API Docs](url)
        - [Accessibility Guidelines](url)
        - Related issue: #456

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any additional notes, constraints, or assumptions that are helpful for implementation.
      placeholder: |
        e.g. "Known limitation: does not support IE11"
