name: New feature request
description: Request a new feature
title: "Component-name: short summary"
labels: 
  - enhancement
  - request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        **💡 Want to contribute?** We'd love your help implementing this! Check out our [Contributing Guidelines](https://github.com/Infineon/infineon-design-system-stencil/blob/master/CONTRIBUTING.md) to learn how you can make it happen.
  - type: textarea
    attributes:
      label: Detailed description of what you want to happen
      description: A clear and concise description of what the feature does.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Upload a screenshot or reference an example if possible
      description: If you are able to illustrate the feature request with an example, please provide a sample reference or a screenshot.
  - type: textarea
    attributes:
      label: Why do you need this feature?
      description: How would your users benefit if we implemented your request? Describe the context and use case.
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Do you have a deadline?
      description: Give us a sense of how urgent this feature is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Free text