name: New Feature Request
description: Request a new feature
title: "Component-name: Short summary"
labels: 
  - enhancement
  - request
body:
  - type: textarea
    attributes:
      label: Detailed description of what you want to happen
      description: A clear and concise description of what the feature does.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Upload a screenshot or reference an example if possible
      description: If you are able to illustrate the feature request with an example, please provide a sample reference or a screenshot.
  - type: textarea
    attributes:
      label: Why do you need this feature?
      description: Describe the context and use case.
  - type: textarea
    attributes:
      label: Do you have a deadline?
      description: Give us a sense of how urgent this feature is.
  - type: textarea
    attributes:
      label: Additional Information
      description: Free text