import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=22450%3A15751",
  {
    variant: { "Show Link": true },
    props: {
      text: figma.string("Text"),
      link: figma.boolean("Show Link", {
        true: figma.nestedProps("Link", {
          "text": figma.string("Label Text"),
        }),
        false: { text: undefined }
      }),
      showClose: figma.boolean("Show Close"), // not supported
      state: figma.enum("State", {
        Error: "error",
        Success: "success",
        Locked: "locked",
        Info: "neutral",
      }),
      icon: figma.enum("State", {
        Error: "cWarningF16",
        Success: "cCheckF16",
        Locked: "lockF16",
        Info: "cWarningF16",
      }),
    },
    example: (props) => html`<ifx-notification variant=${props.state} icon=${props.icon} link-text=${props.link.text} link-href="https://example.com" link-target="_blank">${props.text}</ifx-notification>`,
  },
)

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=22450%3A15751",
  {
    variant: { "Show Link": false },
    props: {
      text: figma.string("Text"),
      showClose: figma.boolean("Show Close"), // not supported
      state: figma.enum("State", {
        Error: "error",
        Success: "success",
        Locked: "locked",
        Info: "neutral",
      }),
      icon: figma.enum("State", {
        Error: "cWarningF16",
        Success: "cCheckF16",
        Locked: "lockF16",
        Info: "cWarningF16",
      }),
    },
    example: (props) => html`<ifx-notification variant=${props.state} icon=${props.icon}>${props.text}</ifx-notification>`,
  },
)
