import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=37224%3A10014",
  {
    props: {
      showLabel: figma.boolean("Show %"),
      value: figma.enum("Progress", {
        "0%": 0,
        "25%": 25,
        "50%": 50,
        "75%": 75,
        "100%": 100,
      }),
      size: figma.enum("Size", {
        "4px": "s",
        "20px": "m",
      }),
    },
    example: (props) => html`
      <ifx-progress-bar
        value=${props.value}
        size=${props.size}
        show-label=${props.showLabel}
      ></ifx-progress-bar>
    `,
  },
)
