import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=72882%3A42414",
  {
    props: {
      label: figma.string("Label"),
      children: figma.enum("Type", {
        Parent: html`<ifx-tree-view-item slot="children">Example child</ifx-tree-view-item>`,
        Item: "",
      }),
      // Unused in example today. Kept for future checkbox-variant support.
      // variant: figma.enum("Variant", {
      //   "No Checkbox": "no-checkbox",
      //   "With Checkbox": "with-checkbox",
      // }),
      // first: figma.boolean("First"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      expanded: figma.nestedProps("_Chevron", {
        expanded: figma.enum("State", {
            Expanded: true,
        })
      })
    },
    example: (props) => html`
    <!-- Example of a tree view item. These must be inside an <ifx-tree-view> component -->
    <ifx-tree-view-item initially-expanded=${props.expanded.expanded} disable-item=${props.disabled} value=${props.label}>
        ${props.label}
        ${props.children}
    </ifx-tree-view-item>`
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=73014%3A4727",
  {
    props: {
      // Unused in example today. Kept for future level-specific templating.
      // nodeLevel: figma.enum("Node Level", {
      //   Parent: "parent",
      //   "1st": "1st",
      //   "2nd": "2nd",
      //   "3rd": "3rd",
      //   "4th": "4th",
      // }),
      // // Unused in example today. Kept for future quantity-based templating.
      // itemAmount: figma.enum("Item Amount", {
      //   "0": "0",
      //   "1": "1",
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      // }),
    },
    example: (_props) => html`<!-- Generic example of a tree view. This does not represent the Figma component accordingly -->
<ifx-tree-view label="Tree Example" aria-label="Tree View">
  <ifx-tree-view-item value="file-1" aria-label="Tree Item">File</ifx-tree-view-item>
  <ifx-tree-view-item value="file-disabled" aria-label="Tree Item" disable-item="true">File
    disabled</ifx-tree-view-item>
  <ifx-tree-view-item initially-expanded="true" value="folder-expanded" aria-label="Tree Item">
    Folder initially expanded
    <ifx-tree-view-item slot="children" initially-selected="true" value="file-selected"
      aria-label="Tree Item">File</ifx-tree-view-item>
    <ifx-tree-view-item slot="children" value="file-normal" aria-label="Tree Item">File</ifx-tree-view-item>
  </ifx-tree-view-item>
  <ifx-tree-view-item value="item-1" aria-label="Tree Item">Normal Item</ifx-tree-view-item>
  <ifx-tree-view-item value="item-2" aria-label="Tree Item">Normal Item</ifx-tree-view-item>
</ifx-tree-view>`,
  },
)

