import * as fs from "node:fs";
import type { IFileUpdater } from "../interfaces.js";
import { escapeRegex } from "./string-utils.js";

/**
 * Generic file updater for marked regions
 */
export class FileUpdater implements IFileUpdater {
	/**
	 * Update a file with generated content in marked regions
	 */
	updateFile(filePath: string, regions: Record<string, string>): boolean {
		if (!fs.existsSync(filePath)) {
			console.error(`❌ File not found: ${filePath}`);
			return false;
		}

		let content = fs.readFileSync(filePath, "utf-8");
		let updated = false;

		for (const [regionName, newContent] of Object.entries(regions)) {
			const [startMarker, endMarker] = this.getMarkersForRegion(regionName);

			if (!startMarker || !endMarker) {
				console.warn(`⚠️  Unknown region: ${regionName}`);
				continue;
			}

			const result = this.replaceRegion(
				content,
				startMarker,
				endMarker,
				newContent,
			);
			if (result !== content) {
				content = result;
				updated = true;
			}
		}

		if (updated) {
			fs.writeFileSync(filePath, content);
			return true;
		}

		return false;
	}

	/**
	 * Check if file has required markers
	 */
	hasMarkers(filePath: string, markers: string[]): boolean {
		if (!fs.existsSync(filePath)) {
			return false;
		}

		const content = fs.readFileSync(filePath, "utf-8");
		return markers.every((marker) => content.includes(marker));
	}

	/**
	 * Get start/end markers for a region name
	 */
	protected getMarkersForRegion(regionName: string): [string, string] {
		const markerMap: Record<string, [string, string]> = {
			imports: [
				"/* <AUTO-GENERATED-IMPORTS> */",
				"/* </AUTO-GENERATED-IMPORTS> */",
			],
			components: [
				"/* <AUTO-GENERATED-COMPONENTS> */",
				"/* </AUTO-GENERATED-COMPONENTS> */",
			],
			"react-navbar-items": [
				"{/* <AUTO-GENERATED-NAVBAR-ITEMS> */}",
				"{/* </AUTO-GENERATED-NAVBAR-ITEMS> */}",
			],
			"react-default-id": [
				"/* <AUTO-GENERATED-DEFAULT-ID> */",
				"/* </AUTO-GENERATED-DEFAULT-ID> */",
			],
			"vue-navbar-items": [
				"<!-- <AUTO-GENERATED-NAVBAR-ITEMS> -->",
				"<!-- </AUTO-GENERATED-NAVBAR-ITEMS> -->",
			],
			"vue-default-id": [
				"/* <AUTO-GENERATED-DEFAULT-ID> */",
				"/* </AUTO-GENERATED-DEFAULT-ID> */",
			],
			"angular-navbar-items": [
				"<!-- <AUTO-GENERATED-NAVBAR-ITEMS> -->",
				"<!-- </AUTO-GENERATED-NAVBAR-ITEMS> -->",
			],
			"angular-default-id": [
				"/* <AUTO-GENERATED-DEFAULT-ID> */",
				"/* </AUTO-GENERATED-DEFAULT-ID> */",
			],
			"html-components": [
				"<!-- <AUTO-GENERATED-COMPONENTS> -->",
				"<!-- </AUTO-GENERATED-COMPONENTS> -->",
			],
			"html-scripts": [
				"/* <AUTO-GENERATED-SCRIPTS> */",
				"/* </AUTO-GENERATED-SCRIPTS> */",
			],
			"html-navbar-items": [
				"<!-- <AUTO-GENERATED-NAVBAR-ITEMS> -->",
				"<!-- </AUTO-GENERATED-NAVBAR-ITEMS> -->",
			],
			"html-default-id": [
				"/* <AUTO-GENERATED-DEFAULT-ID> */",
				"/* </AUTO-GENERATED-DEFAULT-ID> */",
			],
};


		return markerMap[regionName] || ["", ""];
	}

	/**
	 * Replace content between markers
	 */
	protected replaceRegion(
		content: string,
		startMarker: string,
		endMarker: string,
		newContent: string,
	): string {
		const regex = new RegExp(
			`(${escapeRegex(startMarker)})([\\s\\S]*?)(${escapeRegex(endMarker)})`,
			"m",
		);

		if (!regex.test(content)) {
			console.warn(`⚠️  Markers not found: ${startMarker} ... ${endMarker}`);
			return content;
		}

		// Preserve indentation of the start marker
		const match = content.match(regex);
		if (!match) return content;

		const indentMatch = content.substring(0, match.index ?? 0).match(/[ \t]*$/);
		const indent = indentMatch ? indentMatch[0] : "";

		// Add indent to each line of new content
		const indentedContent = newContent
			.split("\n")
			.map((line, index) => {
				if (index === 0) return line; // First line after start marker
				if (line.trim() === "") return "";
				return indent + line;
			})
			.join("\n");

		return content.replace(regex, `$1\n${indentedContent}\n${indent}$3`);
	}
}
