import figma, { html } from "@figma/code-connect/html"


/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Dropdown Menu
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=31285%3A20065",
  {
    props: {
      size: figma.enum("Size", {
        Large: "l",
        Small: "s",
      }),
      header: figma.children("_Dropdown Menu Header Item"),
      items: figma.children("_Dropdown Menu Item")
    },
    example: (props) => html`
    <ifx-dropdown placement="bottom-start" default-open="true" no-close-on-outside-click="false"
        no-close-on-menu-click="false" no-append-to-body="false">
      <ifx-dropdown-trigger-button variant="primary">Dropdown</ifx-dropdown-trigger-button>

      <ifx-dropdown-menu size=${props.size}>
        ${props.header}
        ${props.items}
      </ifx-dropdown-menu>
    </ifx-dropdown>
    `,
  },
)


// _Dropdown Menu Item [variant=Default]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=31285%3A19718",
  {
    props: {
      icon: figma.boolean("Show Icon", {
        true: figma.instance<string>("Icon"),
        false: undefined
      }),
      labelText: figma.string("Label Text"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      error: figma.enum("Variant", {
        Error: true,
      }),
    },
    example: (props) => html`<ifx-dropdown-item icon=${props.icon} href="" target="_self" disabled=${props.disabled} error=${props.error}> 
      ${props.labelText}
    </ifx-dropdown-item>`,
  },
)

// _Dropdown Menu Item [variant=Menu Divider]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=31285%3A19718",
  {
    variant: { "Variant": "Menu Divider" },

    example: () => html`<ifx-dropdown-separator></ifx-dropdown-separator>`,
  },
)


// _Dropdown Entry 
// checkbox and radio are not implemented as of now, so the variants are not included in the code example
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=22402%3A16072",
  {
    props: {
      trash: figma.boolean("Trash"),
      type: figma.enum("Type", {
        Checkbox: "checkbox",
        Radio: "radio",
        Default: "default",
      }),
      selected: figma.boolean("Selected"),
    },
    example: (_props) => html`<ifx-dropdown-item>Label</ifx-dropdown-item>`, 
  },
)

// _Dropdown Menu Header Item [variant=Header Text]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=37691%3A16124",
  {
    variant: { "Variant": "Header Text" },
    props: {
      headerText: figma.string("Header Text"),
    },
    example: (props) => html`<ifx-dropdown-header>${props.headerText}</ifx-dropdown-header>`,
  },
)

// _Dropdown Menu Header Item [variant=Filter Search]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=37691%3A16124",
  {
    variant: { "Variant": "Filter Search" },
    props: {
    },
    example: (_props) => html`<ifx-search-field show-delete-icon="false"></ifx-search-field>`,
  },
)

// Deprecated components from older versions of the design file

// _Dropdown Menu/Default/Filter Search
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=103213%3A2510",
  {
    props: {
      items: figma.children("_Dropdown Menu Item")
    },
    example: (props) => html`
    <ifx-dropdown placement="bottom-start" default-open="true" no-close-on-outside-click="false"
        no-close-on-menu-click="false" no-append-to-body="false">
      <ifx-dropdown-trigger-button variant="primary">Dropdown</ifx-dropdown-trigger-button>

      <ifx-dropdown-menu size="l">
        <ifx-search-field show-delete-icon="false"></ifx-search-field>
        ${props.items}
      </ifx-dropdown-menu>
    </ifx-dropdown>
    `,
  },
)

// _Dropdown Menu/Default/Header Text
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=103213%3A2496",
  {
    props: {
      header: figma.children("_Dropdown Menu Header Item"),
      items: figma.children("_Dropdown Menu Item")
    },
    example: (props) => html`
    <ifx-dropdown placement="bottom-start" default-open="true" no-close-on-outside-click="false"
        no-close-on-menu-click="false" no-append-to-body="false">
      <ifx-dropdown-trigger-button variant="primary">Dropdown</ifx-dropdown-trigger-button>

      <ifx-dropdown-menu size="l">
        ${props.header}
        ${props.items}
      </ifx-dropdown-menu>
    </ifx-dropdown>
    `,
  },
)

// _Dropdown Menu/Default/None
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=103213%3A2484",
  {
    props: {
      items: figma.children("_Dropdown Menu Item")
    },
    example: (props) => html`
    <ifx-dropdown placement="bottom-start" default-open="true" no-close-on-outside-click="false"
        no-close-on-menu-click="false" no-append-to-body="false">
      <ifx-dropdown-trigger-button variant="primary">Dropdown</ifx-dropdown-trigger-button>

      <ifx-dropdown-menu size="l">
        ${props.items}
      </ifx-dropdown-menu>
    </ifx-dropdown>
    `,
  },
)

