import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=80950%3A11140",
  {
    props: {

      label: figma.string("Label Text"),
      icon: figma.boolean("Show left icon", {
        true: figma.instance<string>("Left icon"),
        false: undefined
      }),
      // rightIcon: figma.boolean("Show right icon", {
      //   true: figma.instance("Right icon"),
      //   false: undefined
      // }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      style: figma.enum("Style", {
        Outlined: "outlined",
        "Filled Light": "filled-light",
        "Filled Dark": "filled-dark",
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      })
    },
    example: (props) => html`<ifx-chip theme=${props.style} size=${props.size} icon=${props.icon} placeholder="Placeholder" value="Value1" disabled=${props.disabled}> 
        <ifx-chip-item value="Value1">Item Label 1</ifx-chip-item>
        <ifx-chip-item value="Value2">Item Label 2</ifx-chip-item>
    </ifx-chip>`,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=81061%3A12231",
  {
    props: {
      label: figma.string("Label Text"),
      optionText: figma.string("Option Text"),
      variant: figma.boolean("+more", {
        true: "multi",
        false: "single"
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      }),
      highlighted: figma.boolean("Highlighted"),
    },
    example: (props) => html`<ifx-chip variant=${props.variant} theme="outlined" size=${props.size} placeholder="Placeholder" value=${props.optionText} disabled=${props.disabled}> 
        <ifx-chip-item value=${props.optionText}>${props.optionText}</ifx-chip-item>
        <ifx-chip-item value="other">Other Option</ifx-chip-item>
    </ifx-chip>`,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19374%3A16687",
  {
    props: {
      chips: figma.children("*Chip*")
    },
    example: (props) => html`<div> 
      ${props.chips}
    </div>`,
  },
)
