import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Icon Variant
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=102760%3A5356",
  {
    props: {
      text: figma.string("Text"),
      variant: figma.enum("Variant", {
        Text: "text",
      }),
    },
    variant: {
      "Variant": "Icon",
    },
    example: (_props) => html`<ifx-ai-label variant="icon"></ifx-ai-label>`,
  },
)

// Text Variant
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=102760%3A5356",
  {
    props: {
      text: figma.string("Text"),
      variant: figma.enum("Variant", {
        Text: "text",
      }),
    },
    variant: {
      "Variant": "Text",
    },
    example: (props) => html`<ifx-ai-label variant=${props.variant} divider="true"></ifx-ai-label>`,
  },
)
