import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=22542%3A15403",
  {
    props: {
    //   showDirection: figma.boolean("Show Direction"), // always true
      variant: figma.enum("Variant", {
        Compact: "compact",
        Dismissible: "dismissible",
        Extended: "extended",
      }),
      direction: figma.enum("Direction", {
        "Top Left": "top-start",
        Top: "top",
        "Top Right": "top-end",
        "Bottom Left": "bottom-start",
        Bottom: "bottom",
        "Bottom Right": "bottom-end",
        Left: "left",
        Right: "right",
      }),
      content: figma.enum("Variant", {
        "Dismissible": html`header="Header text here" text="Body text here"`,
        "Extended": html`header="Header text here" text="Body text here" icon="cInfoF16"`,
        "Compact": html`text="Tooltip text here"`,
      }),
      reference: figma.enum("Variant", {
        "Compact": html`This is the reference element. Hover over me to see the tooltip.`,
        "Dismissible": html`This is the reference element. Click me to dismiss the tooltip.`,
        "Extended": html`This is the reference element. Hover over me to see the tooltip.`,

      })
    },
    example: (props) => html`<ifx-tooltip variant=${props.variant} position=${props.direction} ${props.content}>${props.reference}</ifx-tooltip>`,
  },
)