import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12529",
  {
    //  variant based on "_Navigation Logo Large" would be good, but nested variants are not supported yet
    props: {
      // logoProps: figma.nestedProps("_Navigation Logo Large", {
      //   appname: figma.textContent("Application Name"),
      //  ! Not working like this because the text node is only available conditionally
      // }),
      // "showSecondaryNavigation": figma.boolean('Show Secondary Navigation'),
      // "breakpoint": figma.enum('Breakpoint', {
      //   "≥ 1400px": "--1400px",
      //   "≥ 1200px": "--1200px",
      //   "≥ 992px": "--992px",
      //   "≥ 768px": "--768px",
      //   "≥ 360px": "--360px"
      // }),
      // "showNavigationItems": figma.boolean('Show Navigation Items')]
      main: figma.children('_Main Navigation Group'),
      secondary: figma.children('_Secondary Navigation Group'),
    },
    example: (props) => html`<ifx-navbar show-logo-and-appname="true" application-name="Application Name">
      ${props.main}
      ${props.secondary}
    </ifx-navbar>`,
  },
)

// _Main Navigation Group
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12433",
  {
    props: {
      items: figma.children('_Navigation Item')
    },
    example: (props) => html`${props.items}`,
  },
)

// _Secondary Navigation Group 
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A16560",
  {
    props: {
      items: figma.children('_Navigation Item')

      // })
    },
    example: (props) => html`${props.items}`,
  },
)

