import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

// figma.connect(
//   "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
//   {
//     props: {
//       // No matching props could be found for these Figma properties:
//       // "label": figma.string('Label'),
//       // "icon": figma.instance('Icon'),
//       // "showIndicator": figma.boolean('Show Indicator'),
//       // "showLabel": figma.boolean('Show Label'),
//       // "showIcon": figma.boolean('Show Icon'),
//       // "type": figma.enum('Type', {
//       //   "Main Navigation Item": "main-navigation-item",
//       //   "Secondary Navigation Item": "secondary-navigation-item",
//       //   "Search Large": "search-large",
//       //   "Search Small": "search-small",
//       //   "Button Large": "button-large",
//       //   "Button Small": "button-small",
//       //   "Profile": "profile",
//       //   "Sub Navigation Item": "sub-navigation-item"
//       // }),
//       // "expandability": figma.enum('Expandability', {
//       //   "None": "none",
//       //   "Expandable": "expandable",
//       //   "Expanded": "expanded"
//       // }),
//       // "state": figma.enum('State', {
//       //   "Default": "default",
//       //   "Hover": "hover",
//       //   "Pressed": "pressed",
//       //   "Active": "active",
//       //   "Active-Hover": "active-hover"
//       // })
//     },
//     example: (props) => html`<ifx-navbar-item></ifx-navbar-item>`,
//   },
// )

// _Navigation Item[Type=Main Navigation Item]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
  {
    variant: {
      "Type": "Main Navigation Item"
    },
    props: {
      "label": figma.string('Label'),
      // "expandability": figma.enum('Expandability', {
      //   "None": "none",
      //   "Expandable": "expandable",
      //   "Expanded": "expanded"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Pressed": "pressed",
      //   "Active": "active",
      //   "Active-Hover": "active-hover"
      // })
    },
    example: (props) => html`<ifx-navbar-item>${props.label}</ifx-navbar-item>`,
  },
)

// _Navigation Item[Type=Secondary Navigation Item,No Indicator]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
  {
    variant: {
      "Type": "Secondary Navigation Item",
      "Show Indicator": false,
      // "Show Icon": true -> implied by secondary navigation item
    },
    props: {
      // No matching props could be found for these Figma properties:
      "label": figma.string('Label'),
      "icon": figma.instance<string>('Icon'),
      "showIndicator": figma.boolean('Show Indicator'),
      "showLabel": figma.boolean('Show Label'),
      // "showIcon": figma.boolean('Show Icon'),
      // "expandability": figma.enum('Expandability', {W
      //   "None": "none",
      //   "Expandable": "expandable",
      //   "Expanded": "expanded"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Pressed": "pressed",
      //   "Active": "active",
      //   "Active-Hover": "active-hover"
      // })
    },
    example: (props) => html`<ifx-navbar-item icon=${props.icon}>${props.label}</ifx-navbar-item>`,
  },
)


// _Navigation Item[Type=Secondary Navigation Item,With Indicator]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
  {
    variant: {
      "Type": "Secondary Navigation Item",
      "Show Indicator": true,
    },
    props: {
      // No matching props could be found for these Figma properties:
      label: figma.string('Label'),
      icon: figma.instance<string>('Icon'),
      showLabel: figma.boolean('Show Label'),
      // "showIcon": figma.boolean('Show Icon'),
      // "expandability": figma.enum('Expandability', {
      //   "None": "none",
      //   "Expandable": "expandable",
      //   "Expanded": "expanded"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Pressed": "pressed",
      //   "Active": "active",
      //   "Active-Hover": "active-hover"
      // })
      indicator: figma.nestedProps("Indicator", {
        html: figma.enum('Variant', {
          "Number": html`number-indicator="1"`,
          "Dot": html`dot-indicator="true"`
        })
      })
    },
    example: (props) => html`<ifx-navbar-item icon=${props.icon} ${props.indicator.html}>${props.label}</ifx-navbar-item>`,
  },
)


// _Navigation Item[Type=Search Small]
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
  {
    variant: {
      "Type": "Search Small"
    },
    props: {
    },
    example: (_props) => html`<ifx-search-bar slot="search-bar-left" is-open="false"></ifx-search-bar>`,
  },
)

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19241%3A12392",
  {
    variant: {
      "Type": "Search Large"
    },
    props: {
    },
    example: (_props) => html`<ifx-search-bar slot="search-bar-left" is-open="false"></ifx-search-bar>`,
  },
)


// /**


// // _Submenu Items
// figma.connect(
//   "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=31167%3A19091",
//   {
//     props: {
//       // No matching props could be found for these Figma properties:
//       // "multiLevel": figma.boolean('Multi-Level'),
//       // "menuItem": figma.string('Menu Item'),
//       // "showIcon": figma.boolean('Show Icon'),
//       // "icon": figma.instance('Icon'),
//       // "variant": figma.enum('Variant', {
//       //   "Menu Item": "menu-item",
//       //   "Menu Divider": "menu-divider"
//       // }),
//       // "size": figma.enum('Size', {
//       //   "36px": "36px",
//       //   "40px": "40px",
//       //   "None": "none"
//       // }),
//       // "state": figma.enum('State', {
//       //   "Default": "default",
//       //   "Hover": "hover",
//       //   "Pressed": "pressed",
//       //   "None": "none"
//       // })
//     },
//     example: (props) => <NavbarItem />,
//   },
// )


// // _Sub Navigation Group
// figma.connect(
//   "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=81445%3A16438",
//   {
//     props: {
//       // No matching props could be found for these Figma properties:
//       // "items": figma.enum('Items', {
//       //   "1": "1",
//       //   "2": "2",
//       //   "3": "3",
//       //   "4": "4",
//       //   "5": "5",
//       //   "6": "6"
//       // })
//     },
//     example: (props) => <NavbarItem />,
//   },
// )



// Submenu Dropdown
// figma.connect(
//   "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=31017%3A18511",
//   {
//     props: {
//       // No matching props could be found for these Figma properties:
//       // "variant": figma.enum('Variant', {
//       //   "> Level 2": "--level-2",
//       //   "> Level 3": "--level-3",
//       //   "> Level 1": "--level-1"
//       // })
//     },
//     example: (props) => <NavbarItem />,
//   },
// )
