import {
	afterNextRender,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	Injector,
	type OnInit,
	signal,
} from "@angular/core";
import { IfxNavbar } from "@infineon/infineon-design-system-angular/standalone";
import Prism from "prismjs";
import "prismjs/components/prism-markup.js";
import "prismjs/components/prism-javascript.js";
import "prismjs/components/prism-typescript.js";

import packageJson from "../../package.json";

const declaredVersion =
	packageJson.dependencies["@infineon/infineon-design-system-angular"];

import { version as installedVersion } from "@infineon/infineon-design-system-angular/package.json";

/* <AUTO-GENERATED-IMPORTS> */
import { IfxAccordionExample } from './generated/ifx-accordion-example/ifx-accordion-example';
import { IfxActionListExample } from './generated/ifx-action-list-example/ifx-action-list-example';
import { IfxAlertExample } from './generated/ifx-alert-example/ifx-alert-example';
import { IfxAiLabelExample } from './generated/ifx-ai-label-example/ifx-ai-label-example';
import { IfxButtonExample } from './generated/ifx-button-example/ifx-button-example';
import { IfxCardExample } from './generated/ifx-card-example/ifx-card-example';
import { IfxCheckboxExample } from './generated/ifx-checkbox-example/ifx-checkbox-example';
import { IfxCheckboxGroupExample } from './generated/ifx-checkbox-group-example/ifx-checkbox-group-example';
import { IfxChipExample } from './generated/ifx-chip-example/ifx-chip-example';
import { IfxContentSwitcherExample } from './generated/ifx-content-switcher-example/ifx-content-switcher-example';
import { IfxDatePickerExample } from './generated/ifx-date-picker-example/ifx-date-picker-example';
import { IfxDropdownExample } from './generated/ifx-dropdown-example/ifx-dropdown-example';
import { IfxFooterMediumExample } from './generated/ifx-footer-example-medium/ifx-footer-example-medium';
import { IfxIconButtonExample } from './generated/ifx-icon-button-example/ifx-icon-button-example';
import { IfxIndicatorExample } from './generated/ifx-indicator-example/ifx-indicator-example';
import { IfxLinkExample } from './generated/ifx-link-example/ifx-link-example';
import { IfxNavbarExample } from './generated/ifx-navbar-example/ifx-navbar-example';
import { IfxSidebarExample } from './generated/ifx-sidebar-example/ifx-sidebar-example';
import { IfxNotificationExample } from './generated/ifx-notification-example/ifx-notification-example';
import { IfxPaginationExample } from './generated/ifx-pagination-example/ifx-pagination-example';
import { IfxProgressBarExample } from './generated/ifx-progress-bar-example/ifx-progress-bar-example';
import { IfxRadioButtonExample } from './generated/ifx-radio-button-example/ifx-radio-button-example';
import { IfxRadioButtonGroupExample } from './generated/ifx-radio-button-group-example/ifx-radio-button-group-example';
import { IfxSearchBarExample } from './generated/ifx-search-bar-example/ifx-search-bar-example';
import { IfxSearchFieldExample } from './generated/ifx-search-field-example/ifx-search-field-example';
import { IfxSegmentedControlExample } from './generated/ifx-segmented-control-example/ifx-segmented-control-example';
import { IfxSelectExample } from './generated/ifx-select-example/ifx-select-example';
import { IfxSpinnerExample } from './generated/ifx-spinner-example/ifx-spinner-example';
import { IfxStatusExample } from './generated/ifx-status-example/ifx-status-example';
import { IfxStepperExample } from './generated/ifx-stepper-example/ifx-stepper-example';
import { IfxStepperCompactExample } from './generated/ifx-stepper-example-compact/ifx-stepper-example-compact';
import { IfxSwitchExample } from './generated/ifx-switch-example/ifx-switch-example';
import { IfxBasicTableExample } from './generated/ifx-basic-table-example/ifx-basic-table-example';
import { IfxTableDefaultStateExample } from './generated/ifx-table-example-defaultstate/ifx-table-example-defaultstate';
import { IfxTabsExample } from './generated/ifx-tabs-example/ifx-tabs-example';
import { IfxTextFieldExample } from './generated/ifx-text-field-example/ifx-text-field-example';
import { IfxTextareaExample } from './generated/ifx-textarea-example/ifx-textarea-example';
import { IfxTooltipExample } from './generated/ifx-tooltip-example/ifx-tooltip-example';
/* </AUTO-GENERATED-IMPORTS> */

// Manual examples
import { ModalExample } from "./manual/modal-example/modal-example";

@Component({
	selector: "app-root",
	imports: [
		IfxNavbar,
		ModalExample,
		/* <AUTO-GENERATED-COMPONENTS> */
IfxAccordionExample, IfxActionListExample, IfxAlertExample, IfxAiLabelExample, IfxButtonExample, IfxCardExample, IfxCheckboxExample, IfxCheckboxGroupExample, IfxChipExample, IfxContentSwitcherExample, IfxDatePickerExample, IfxDropdownExample, IfxFooterMediumExample, IfxIconButtonExample, IfxIndicatorExample, IfxLinkExample, IfxNavbarExample, IfxSidebarExample, IfxNotificationExample, IfxPaginationExample, IfxProgressBarExample, IfxRadioButtonExample, IfxRadioButtonGroupExample, IfxSearchBarExample, IfxSearchFieldExample, IfxSegmentedControlExample, IfxSelectExample, IfxSpinnerExample, IfxStatusExample, IfxStepperExample, IfxStepperCompactExample, IfxSwitchExample, IfxBasicTableExample, IfxTableDefaultStateExample, IfxTabsExample, IfxTextFieldExample, IfxTextareaExample, IfxTooltipExample
		/* </AUTO-GENERATED-COMPONENTS> */
	],
	templateUrl: "./app.html",
	styleUrl: "./app.scss",
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class App implements OnInit {
	protected readonly title = signal("angular-standalone-example");
	protected version = "";

	constructor(private injector: Injector) {
		afterNextRender(
			() => {
				Prism.highlightAll();
			},
			{ injector: this.injector },
		);
	}

	ngOnInit() {
		// Component initialization

		if (declaredVersion.includes("workspace")) {
			this.version = "workspace";
		} else {
			this.version = installedVersion;
		}
	}
}
