<script setup lang="ts">
import Prism from "prismjs";
import { nextTick, onMounted } from "vue";
import "prismjs/components/prism-markup";

// @ts-expect-error
import packageJson from "../package.json";

const declaredVersion = (packageJson.dependencies as Record<string, string>)[
	"@infineon/infineon-design-system-vue"
];

import { version as installedVersion } from "@infineon/infineon-design-system-vue/package.json";

/* <AUTO-GENERATED-IMPORTS> */
import IfxAccordionExample from './generated/IfxAccordionExample.vue';
import IfxActionListExample from './generated/IfxActionListExample.vue';
import IfxCardExample from './generated/IfxCardExample.vue';
import IfxCheckboxExample from './generated/IfxCheckboxExample.vue';
import IfxCheckboxGroupExample from './generated/IfxCheckboxGroupExample.vue';
import IfxDatePickerExample from './generated/IfxDatePickerExample.vue';
import IfxIndicatorExample from './generated/IfxIndicatorExample.vue';
import IfxLinkExample from './generated/IfxLinkExample.vue';
import IfxPaginationExample from './generated/IfxPaginationExample.vue';
import IfxProgressBarExample from './generated/IfxProgressBarExample.vue';
import IfxRadioButtonExample from './generated/IfxRadioButtonExample.vue';
import IfxRadioButtonGroupExample from './generated/IfxRadioButtonGroupExample.vue';
import IfxSearchBarExample from './generated/IfxSearchBarExample.vue';
import IfxSearchFieldExample from './generated/IfxSearchFieldExample.vue';
import IfxSelectExample from './generated/IfxSelectExample.vue';
import IfxSpinnerExample from './generated/IfxSpinnerExample.vue';
import IfxStatusExample from './generated/IfxStatusExample.vue';
import IfxStepperExample from './generated/IfxStepperExample.vue';
import IfxStepperCompactExample from './generated/IfxStepperCompactExample.vue';
import IfxSwitchExample from './generated/IfxSwitchExample.vue';
import IfxBasicTableExample from './generated/IfxBasicTableExample.vue';
import IfxTableDefaultStateExample from './generated/IfxTableDefaultStateExample.vue';
import IfxTextareaExample from './generated/IfxTextareaExample.vue';
/* </AUTO-GENERATED-IMPORTS> */

// Manual examples
import ModalExample from "./manual/ModalExample.vue";

// Highlight code blocks on mount and updates
onMounted(() => {
	nextTick(() => {
		Prism.highlightAll();
	});
});
</script>

<template>
  <ifx-navbar 
    show-logo-and-appname="true" 
    application-name="Infineon Design System - Vue Example" 
    :fixed="false"
  />

  <div class="version-info">@infineon/infineon-design-system-vue@{{ declaredVersion.includes('workspace') ? 'workspace' : installedVersion }}</div>

  <div class="components">
    <!-- <AUTO-GENERATED-COMPONENTS> -->
    <section id="ifx-accordion-example" class="component-example">
          <h2>Accordion</h2>
          <div class="demo">
            <IfxAccordionExample />
          </div>
        </section>

        <section id="ifx-action-list-example" class="component-example">
          <h2>Action List</h2>
          <div class="demo">
            <IfxActionListExample />
          </div>
        </section>

        <section id="ifx-card-example" class="component-example">
          <h2>Card</h2>
          <div class="demo">
            <IfxCardExample />
          </div>
        </section>

        <section id="ifx-checkbox-example" class="component-example">
          <h2>Checkbox</h2>
          <div class="demo">
            <IfxCheckboxExample />
          </div>
        </section>

        <section id="ifx-checkbox-group-example" class="component-example">
          <h2>Checkbox Group</h2>
          <div class="demo">
            <IfxCheckboxGroupExample />
          </div>
        </section>

        <section id="ifx-date-picker-example" class="component-example">
          <h2>Date Picker</h2>
          <div class="demo">
            <IfxDatePickerExample />
          </div>
        </section>

        <section id="ifx-indicator-example" class="component-example">
          <h2>Indicator</h2>
          <div class="demo">
            <IfxIndicatorExample />
          </div>
        </section>

        <section id="ifx-link-example" class="component-example">
          <h2>Link</h2>
          <div class="demo">
            <IfxLinkExample />
          </div>
        </section>

        <section id="ifx-pagination-example" class="component-example">
          <h2>Pagination</h2>
          <div class="demo">
            <IfxPaginationExample />
          </div>
        </section>

        <section id="ifx-progress-bar-example" class="component-example">
          <h2>Progress Bar</h2>
          <div class="demo">
            <IfxProgressBarExample />
          </div>
        </section>

        <section id="ifx-radio-button-example" class="component-example">
          <h2>Radio Button</h2>
          <div class="demo">
            <IfxRadioButtonExample />
          </div>
        </section>

        <section id="ifx-radio-button-group-example" class="component-example">
          <h2>Radio Button Group</h2>
          <div class="demo">
            <IfxRadioButtonGroupExample />
          </div>
        </section>

        <section id="ifx-search-bar-example" class="component-example">
          <h2>Search Bar</h2>
          <div class="demo">
            <IfxSearchBarExample />
          </div>
        </section>

        <section id="ifx-search-field-example" class="component-example">
          <h2>Search Field</h2>
          <div class="demo">
            <IfxSearchFieldExample />
          </div>
        </section>

        <section id="ifx-select-example" class="component-example">
          <h2>Select/Single Select</h2>
          <div class="demo">
            <IfxSelectExample />
          </div>
        </section>

        <section id="ifx-spinner-example" class="component-example">
          <h2>Spinner</h2>
          <div class="demo">
            <IfxSpinnerExample />
          </div>
        </section>

        <section id="ifx-status-example" class="component-example">
          <h2>Status</h2>
          <div class="demo">
            <IfxStatusExample />
          </div>
        </section>

        <section id="ifx-stepper-example" class="component-example">
          <h2>Stepper</h2>
          <div class="demo">
            <IfxStepperExample />
          </div>
        </section>

        <section id="ifx-stepper-example-compact" class="component-example">
          <h2>Stepper - Compact</h2>
          <div class="demo">
            <IfxStepperCompactExample />
          </div>
        </section>

        <section id="ifx-switch-example" class="component-example">
          <h2>Switch</h2>
          <div class="demo">
            <IfxSwitchExample />
          </div>
        </section>

        <section id="ifx-basic-table-example" class="component-example">
          <h2>Table (basic)</h2>
          <div class="demo">
            <IfxBasicTableExample />
          </div>
        </section>

        <section id="ifx-table-example-defaultstate" class="component-example">
          <h2>Table (advanced) - DefaultState</h2>
          <div class="demo">
            <IfxTableDefaultStateExample />
          </div>
        </section>

        <section id="ifx-textarea-example" class="component-example">
          <h2>Textarea</h2>
          <div class="demo">
            <IfxTextareaExample />
          </div>
        </section>
    <!-- </AUTO-GENERATED-COMPONENTS> -->

    <!-- Manual examples that require custom logic -->
    <section id="modal-example" class="component-example">
      <h2>Modal (Manual Example)</h2>
      <div class="demo">
        <ModalExample />
      </div>
    </section>
  </div>
</template>

<style>
body {
	background-color: #f7f7f7;
	margin: 0;
  font-family: "Source Sans 3", sans-serif;
}

.version-info {
	background-color: white;
	padding: 8px 16px;
	margin: 0;
	font-size: 14px;
	color: #666;
	font-family: monospace;
}

.components {
	display: flex;
	flex-direction: column;
	gap: 16px;
	padding: 16px;
}

.components > section {
	background-color: #ffffff;
	padding: 12px 20px;
}

h2 {
	margin: 4px 0px 12px 0px;
}

summary {
	cursor: pointer;
	font-weight: bold;
	margin-top: 20px;
}

.code-details {
	margin-top: 16px;
}

.code-details .code-blocks h3 {
	margin: 16px 0 8px 0;
	font-size: 14px;
	font-weight: 600;
	color: #333;
}

.code-details .code-blocks h3:first-child {
	margin-top: 0;
}

.code-blocks {
	margin-top: 12px;
}
</style>
