import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=11700%3A6732",
  {
    props: {
      largeIcon: figma.instance("Large Icon"),
      smallIcon: figma.instance("Small Icon"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Secondary: "secondary",
        Tertiary: "tertiary",
      }),
      shape: figma.enum("Style", {
        Round: "round",
        Square: "square",
      }),
      size: figma.enum("Size", {
        "20px": "xs",
        "32px": "s",
        "36px": "m",
        "40px": "l",
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      }),
    },
    example: (props) => html`<ifx-icon-button variant=${props.variant} shape=${props.shape} size=${props.size} icon=${props.largeIcon} disabled=${props.disabled}></ifx-icon-button>`,
  },
)
