import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=19130%3A14002",
  {
    props: {
      buttons: figma.children(["Button", "Link"]),
      title: figma.boolean("Title+Desc", {
        true: figma.string("Title"),
        false: undefined
      }),
      overline: figma.boolean("Overline", {
        true: figma.string("Overline Text"),
        false: undefined,
      }),
      description: figma.boolean("Title+Desc", {
        true: figma.string("Description"),
        false: undefined
      }),
      image: figma.boolean("Image", {
        true: html`<ifx-card-image slot="img" position="" src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg"></ifx-card-image>`,
        false: undefined
      }),
    },
    example: (props) => html`<ifx-card direction="vertical" href="" target="_blank" >
      ${props.image}
      <ifx-card-overline>${props.overline}</ifx-card-overline>
      <ifx-card-headline>${props.title}</ifx-card-headline>
      <ifx-card-text>${props.description}</ifx-card-text>
      <ifx-card-links slot="buttons">${props.buttons}</ifx-card-links>
    </ifx-card>`,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=36184%3A3797",
  {
    props: {
      image: figma.children("Image"),
      description: figma.boolean("Desc", {
        true: html`<ifx-card-text>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et</ifx-card-text>`,
        false: undefined
      }),
      buttons: figma.children(["Button", "Link"]),
      // align: figma.enum("Align", {
      //   Left: "left",
      //   Right: "right",
      // }),
    },
    example: (props) => html`<ifx-card direction="horizontal" href="" target="_blank"> 
      ${props.image}
      <ifx-card-overline>Example Overline</ifx-card-overline>
      <ifx-card-headline>Example Headline</ifx-card-headline>
      ${props.description}
      <ifx-card-links slot="buttons">${props.buttons}</ifx-card-links>
    </ifx-card>`,
  },
)
