import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=33581%3A21725",
  {
    props: {
      variant: figma.enum("Variant", {
        Default: "default",
        Brand: "brand",
      }),
      size: figma.enum("Size", {
        "24px": "s",
        "40px": "m",
      }),
    },
    example: (props) => html`<ifx-spinner size=${props.size} variant=${props.variant}></ifx-spinner>`,
  },
)
