import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=89394%3A2115",
  {
    props: {
      showClose: figma.boolean("Show Close"),
      title: figma.string("Title"),
      supportText: figma.string("Support text"),
      action: figma.enum("Action", {
        Buttons: "buttons",
        Links: "links",
      }),
      position: figma.enum("Direction", {
        "Bottom left": "bottom-start",
        Bottom: "bottom",
        "Top left": "top-start",
        "Bottom right": "bottom-end",
        Top: "top",
        "Top right": "top-end",
        Left: "left",
        Right: "right",
        None: "auto",
      }),
      actions: figma.boolean("Show Actions", {
        true: figma.children(["Link", "Button"]),
        false: undefined
      }),
    },
    example: (props) => html`<ifx-popover popover-title=${props.title} text=${props.supportText} position=${props.position} open>

      <div slot="content">${props.actions}</div>
    </ifx-popover>`,
  },
)
