import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=59371%3A9241",
  {
    props: {
        "caption": figma.boolean('Show Caption', {
            true: figma.nestedProps('Caption', {
                "text": figma.string('Caption text'),
            }),
            false: { "text": undefined }
        }),
        "label": figma.nestedProps('Labels', {
            "text": figma.string('Label text'),
        }),
        "required": figma.nestedProps('Labels', {
            "required": figma.enum('Variant', {
                'Required': true,
            }),
        }),
        placeholderText: figma.string("Placeholder Text"),
        inputText: figma.string("Input Text"),
        disabled: figma.enum("State", {
            Disabled: true,
        }),
        error: figma.enum("State", {
            "Error": true,
            "Active-Error": true,
        }),
        readOnly: figma.enum("State", {
            "Read only": true,
        }),
    },
        
    example: (props) => html`<ifx-textarea label=${props.label.text} caption=${props.caption.text} placeholder=${props.placeholderText} name="textarea" value=${props.inputText} rows="4" disabled=${props.disabled} error=${props.error} read-only=${props.readOnly} required=${props.required.required}></ifx-textarea>`,
  },
)