import * as path from "node:path";
import { HTMLCodeFormatter } from "../formatters/html-formatter.js";
import type {
	GenerationResult,
	GeneratorConfig,
	IExampleGenerator,
} from "../interfaces.js";
import type { ComponentInfo } from "../types.js";
import { FileUpdater } from "../utils/file-updater.js";

/**
 * HTML/Web Components example generator
 */
export class HTMLExampleGenerator implements IExampleGenerator {
	private formatter: HTMLCodeFormatter;
	private fileUpdater: FileUpdater;

	constructor() {
		this.formatter = new HTMLCodeFormatter();
		this.fileUpdater = new FileUpdater();
	}

	/**
	 * Generate HTML examples
	 */
	generate(
		components: ComponentInfo[],
		config: GeneratorConfig,
	): GenerationResult {
		const result: GenerationResult = {
			success: true,
			filesGenerated: [],
			filesUpdated: [],
			errors: [],
		};

		try {
			const htmlPath = path.join(
				config.outputDir,
				config.filePath || "index.html",
			);

			// Validate file exists
			if (!this.validate(config)) {
				result.success = false;
				result.errors?.push(
					`HTML file not found or missing markers: ${htmlPath}`,
				);
				return result;
			}

			// Generate component HTML sections
			const componentSections = components
				.map((c) => this.formatter.formatComponent(c, { indent: "        " }))
				.join("\n");

			// Generate event handlers
			const generatedHandlers = components
				.map((c) => this.formatter.formatEventHandlers(c, { indent: "  " }))
				.filter((h) => h.length > 0)
				.join("\n\n    ");

			// Update the HTML file
			const updated = this.fileUpdater.updateFile(htmlPath, {
				"html-components": componentSections,
				"html-scripts": generatedHandlers,
			});

			if (updated) {
				result.filesUpdated.push(htmlPath);
			} else {
				// File exists and is valid, even if not updated (no changes)
				result.filesUpdated.push(htmlPath);
			}
		} catch (error) {
			result.success = false;
			result.errors?.push(
				error instanceof Error ? error.message : String(error),
			);
		}

		return result;
	}

	/**
	 * Get generator name
	 */
	getName(): string {
		return "HTML/Web Components";
	}

	/**
	 * Validate output directory and file structure
	 */
	validate(config: GeneratorConfig): boolean {
		const htmlPath = path.join(
			config.outputDir,
			config.filePath || "index.html",
		);

		return this.fileUpdater.hasMarkers(htmlPath, [
			"<!-- <AUTO-GENERATED-COMPONENTS> -->",
			"<!-- </AUTO-GENERATED-COMPONENTS> -->",
			"/* <AUTO-GENERATED-SCRIPTS> */",
			"/* </AUTO-GENERATED-SCRIPTS> */",
		]);
	}
}
