import * as fs from "node:fs";
import * as path from "node:path";
import {
	ALL_COMPONENTS_ID,
	buildAlphabeticalNavbarGroups,
	formatTitle,
	toPascalCase,
	VueCodeFormatter,
} from "@infineon/dds-tooling";
import type {
	GenerationResult,
	GeneratorConfig,
	IExampleGenerator,
} from "../interfaces.js";
import type { ComponentInfo } from "../types.js";
import { FileUpdater } from "../utils/file-updater.js";

/**
 * Vue example generator
 */
export class VueExampleGenerator implements IExampleGenerator {
	private formatter: VueCodeFormatter;
	private fileUpdater: FileUpdater;

	constructor() {
		this.formatter = new VueCodeFormatter();
		this.fileUpdater = new FileUpdater();
	}

	/**
	 * Generate Vue examples
	 */
	generate(
		components: ComponentInfo[],
		config: GeneratorConfig,
	): GenerationResult {
		const result: GenerationResult = {
			success: true,
			filesGenerated: [],
			filesUpdated: [],
			errors: [],
		};

		try {
			// Ensure directory structure exists
			this.ensureDirectoryStructure(config.outputDir);

			// Generate component files and navbar items
			const imports: string[] = [];
			const componentTags: string[] = [];
			const navbarEntries: Array<{ exampleId: string; title: string }> = [];
			let defaultExampleId = "";

			for (const component of components) {
				const componentName = toPascalCase(component.component);
				const storyNameSuffix =
					component.storyName && component.storyName !== "Default"
						? component.storyName.replace(/\s+/g, "")
						: "";
				const componentClassName = `${componentName}${storyNameSuffix}Example`;
				const componentCode = this.formatter.formatComponentFile(component);
				const filePath = path.join(
					config.outputDir,
					"src",
					"generated",
					`${componentClassName}.vue`,
				);

				fs.writeFileSync(filePath, componentCode);
				result.filesGenerated.push(filePath);

				// Prepare imports and template sections for App.vue
				const idSuffix =
					component.storyName && component.storyName !== "Default"
						? `-${component.storyName.toLowerCase().replace(/\s+/g, "-")}`
						: "";
				imports.push(
					`import ${componentClassName} from './generated/${componentClassName}.vue';`,
				);

				const exampleId = `${component.component}-example${idSuffix}`;
				if (!defaultExampleId) {
					defaultExampleId = exampleId;
				}
				const title = formatTitle(component.title, component.component, component.storyName);

				navbarEntries.push({ exampleId, title });

				componentTags.push(
					`    <section v-if="activeId === '${exampleId}' || activeId === '${ALL_COMPONENTS_ID}'" id="${exampleId}" class="component-example">\n` +
						`      <h2>${title}</h2>\n` +
						`      <div class="demo">\n` +
						`        <${componentClassName} />\n` +
						`      </div>\n` +
						`    </section>`,
				);
			}

			// Update App.vue
			const appPath = path.join(config.outputDir, "src", "App.vue");

			if (!this.validate(config)) {
				result.success = false;
				result.errors?.push(`App.vue not found or missing markers: ${appPath}`);
				return result;
			}

			const importsContent = imports.join("\n");
			const componentsContent = componentTags.join("\n\n");
			const navbarContent = buildAlphabeticalNavbarGroups(
				navbarEntries,
				(label, items) => {
					const groupItems = items
						.map(
							(item) =>
								`  <ifx-navbar-item href="#${item.exampleId}">${item.title}</ifx-navbar-item>`,
						)
						.join("\n");

					return [
						'<ifx-navbar-item icon="block16" slot="left-item" href="" target="_self">',
						`  ${label}`,
						groupItems,
						"</ifx-navbar-item>",
					].join("\n");
				},
			);
			const navbarWithAllComponents = [
				navbarContent,
				`<ifx-navbar-item href="#${ALL_COMPONENTS_ID}" slot="left-item">All Components</ifx-navbar-item>`,
			].join("\n");

			const updated = this.fileUpdater.updateFile(appPath, {
				imports: importsContent,
				"html-components": componentsContent,
				"vue-navbar-items": navbarWithAllComponents,
				"vue-default-id": `return "${defaultExampleId || "ifx-accordion-example"}";`,
			});

			if (updated) {
				result.filesUpdated.push(appPath);
			}
		} catch (error) {
			result.success = false;
			result.errors?.push(
				error instanceof Error ? error.message : String(error),
			);
		}

		return result;
	}

	/**
	 * Get generator name
	 */
	getName(): string {
		return "Vue";
	}

	/**
	 * Validate output directory and file structure
	 */
	validate(config: GeneratorConfig): boolean {
		const appPath = path.join(config.outputDir, "src", "App.vue");

		return this.fileUpdater.hasMarkers(appPath, [
			"/* <AUTO-GENERATED-IMPORTS> */",
			"/* </AUTO-GENERATED-IMPORTS> */",
			"<!-- <AUTO-GENERATED-NAVBAR-ITEMS> -->",
			"<!-- </AUTO-GENERATED-NAVBAR-ITEMS> -->",
			"/* <AUTO-GENERATED-DEFAULT-ID> */",
			"/* </AUTO-GENERATED-DEFAULT-ID> */",
			"<!-- <AUTO-GENERATED-COMPONENTS> -->",
			"<!-- </AUTO-GENERATED-COMPONENTS> -->",
		]);
	}

	/**
	 * Ensure directory structure exists
	 */
	private ensureDirectoryStructure(outputDir: string): void {
		const dirs = [
			outputDir,
			path.join(outputDir, "src"),
			path.join(outputDir, "src", "generated"),
		];

		dirs.forEach((dir) => {
			if (!fs.existsSync(dir)) {
				fs.mkdirSync(dir, { recursive: true });
			}
		});
	}
}
