import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Variant number
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=14392%3A7580",
  {
    props: {
      number: figma.string("Number"),
      variant: figma.enum("Variant", {
        Number: "number",
        Dot: "dot",
      }),
      inverted: figma.enum("Style", {
        "Inverted": true,
      })
    },
    variant: {
      "Variant": "Number",
    },
    example: (props) => html`<ifx-indicator variant="number" number=${props.number} inverted=${props.inverted}/>`,
  },
)

// Variant dot
figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=14392%3A7580",
  {
    props: {
      number: figma.string("Number"),
      variant: figma.enum("Variant", {
        Number: "number",
        Dot: "dot",
      }),
    },
    example: (_props) => html`<ifx-indicator variant="dot"/>`,
  },
)
