import { NgModule, provideBrowserGlobalErrorListeners } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { InfineonDesignSystemModule } from "@infineon/infineon-design-system-angular";

import { App } from "./app";

/* <AUTO-GENERATED-IMPORTS> */
import { IfxAccordionExample } from './generated/ifx-accordion-example/ifx-accordion-example';
import { IfxActionListExample } from './generated/ifx-action-list-example/ifx-action-list-example';
import { IfxAlertExample } from './generated/ifx-alert-example/ifx-alert-example';
import { IfxButtonExample } from './generated/ifx-button-example/ifx-button-example';
import { IfxCardExample } from './generated/ifx-card-example/ifx-card-example';
import { IfxCheckboxExample } from './generated/ifx-checkbox-example/ifx-checkbox-example';
import { IfxCheckboxGroupExample } from './generated/ifx-checkbox-group-example/ifx-checkbox-group-example';
import { IfxChipExample } from './generated/ifx-chip-example/ifx-chip-example';
import { IfxContentSwitcherExample } from './generated/ifx-content-switcher-example/ifx-content-switcher-example';
import { IfxDatePickerExample } from './generated/ifx-date-picker-example/ifx-date-picker-example';
import { IfxDropdownExample } from './generated/ifx-dropdown-example/ifx-dropdown-example';
import { IfxFooterMediumExample } from './generated/ifx-footer-example-medium/ifx-footer-example-medium';
import { IfxIconButtonExample } from './generated/ifx-icon-button-example/ifx-icon-button-example';
import { IfxIndicatorExample } from './generated/ifx-indicator-example/ifx-indicator-example';
import { IfxLinkExample } from './generated/ifx-link-example/ifx-link-example';
import { IfxNavbarExample } from './generated/ifx-navbar-example/ifx-navbar-example';
import { IfxSidebarExample } from './generated/ifx-sidebar-example/ifx-sidebar-example';
import { IfxNotificationExample } from './generated/ifx-notification-example/ifx-notification-example';
import { IfxPaginationExample } from './generated/ifx-pagination-example/ifx-pagination-example';
import { IfxProgressBarExample } from './generated/ifx-progress-bar-example/ifx-progress-bar-example';
import { IfxRadioButtonExample } from './generated/ifx-radio-button-example/ifx-radio-button-example';
import { IfxRadioButtonGroupExample } from './generated/ifx-radio-button-group-example/ifx-radio-button-group-example';
import { IfxSearchBarExample } from './generated/ifx-search-bar-example/ifx-search-bar-example';
import { IfxSearchFieldExample } from './generated/ifx-search-field-example/ifx-search-field-example';
import { IfxSegmentedControlExample } from './generated/ifx-segmented-control-example/ifx-segmented-control-example';
import { IfxSelectExample } from './generated/ifx-select-example/ifx-select-example';
import { IfxSpinnerExample } from './generated/ifx-spinner-example/ifx-spinner-example';
import { IfxStatusExample } from './generated/ifx-status-example/ifx-status-example';
import { IfxStepperExample } from './generated/ifx-stepper-example/ifx-stepper-example';
import { IfxStepperCompactExample } from './generated/ifx-stepper-example-compact/ifx-stepper-example-compact';
import { IfxSwitchExample } from './generated/ifx-switch-example/ifx-switch-example';
import { IfxBasicTableExample } from './generated/ifx-basic-table-example/ifx-basic-table-example';
import { IfxTableDefaultStateExample } from './generated/ifx-table-example-defaultstate/ifx-table-example-defaultstate';
import { IfxTabsExample } from './generated/ifx-tabs-example/ifx-tabs-example';
import { IfxTextFieldExample } from './generated/ifx-text-field-example/ifx-text-field-example';
import { IfxTextareaExample } from './generated/ifx-textarea-example/ifx-textarea-example';
import { IfxTooltipExample } from './generated/ifx-tooltip-example/ifx-tooltip-example';
/* </AUTO-GENERATED-IMPORTS> */

@NgModule({
	declarations: [
		App,
		/* <AUTO-GENERATED-COMPONENTS> */
IfxAccordionExample,
		    IfxActionListExample,
		    IfxAlertExample,
		    IfxButtonExample,
		    IfxCardExample,
		    IfxCheckboxExample,
		    IfxCheckboxGroupExample,
		    IfxChipExample,
		    IfxContentSwitcherExample,
		    IfxDatePickerExample,
		    IfxDropdownExample,
		    IfxFooterMediumExample,
		    IfxIconButtonExample,
		    IfxIndicatorExample,
		    IfxLinkExample,
		    IfxNavbarExample,
		    IfxSidebarExample,
		    IfxNotificationExample,
		    IfxPaginationExample,
		    IfxProgressBarExample,
		    IfxRadioButtonExample,
		    IfxRadioButtonGroupExample,
		    IfxSearchBarExample,
		    IfxSearchFieldExample,
		    IfxSegmentedControlExample,
		    IfxSelectExample,
		    IfxSpinnerExample,
		    IfxStatusExample,
		    IfxStepperExample,
		    IfxStepperCompactExample,
		    IfxSwitchExample,
		    IfxBasicTableExample,
		    IfxTableDefaultStateExample,
		    IfxTabsExample,
		    IfxTextFieldExample,
		    IfxTextareaExample,
		    IfxTooltipExample
		/* </AUTO-GENERATED-COMPONENTS> */
	],
	imports: [BrowserModule, InfineonDesignSystemModule.forRoot()],
	providers: [
		provideBrowserGlobalErrorListeners(),
	],
	bootstrap: [App],
})
export class AppModule {}
