import { NgModule, provideBrowserGlobalErrorListeners } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { InfineonDesignSystemModule } from "@infineon/infineon-design-system-angular";

import { App } from "./app";

/* <AUTO-GENERATED-IMPORTS> */
import { IfxAccordionExample } from './generated/ifx-accordion-example/ifx-accordion-example';
import { IfxActionListExample } from './generated/ifx-action-list-example/ifx-action-list-example';
import { IfxCardExample } from './generated/ifx-card-example/ifx-card-example';
import { IfxCheckboxExample } from './generated/ifx-checkbox-example/ifx-checkbox-example';
import { IfxCheckboxGroupExample } from './generated/ifx-checkbox-group-example/ifx-checkbox-group-example';
import { IfxDatePickerExample } from './generated/ifx-date-picker-example/ifx-date-picker-example';
import { IfxIndicatorExample } from './generated/ifx-indicator-example/ifx-indicator-example';
import { IfxLinkExample } from './generated/ifx-link-example/ifx-link-example';
import { IfxPaginationExample } from './generated/ifx-pagination-example/ifx-pagination-example';
import { IfxProgressBarExample } from './generated/ifx-progress-bar-example/ifx-progress-bar-example';
import { IfxRadioButtonExample } from './generated/ifx-radio-button-example/ifx-radio-button-example';
import { IfxRadioButtonGroupExample } from './generated/ifx-radio-button-group-example/ifx-radio-button-group-example';
import { IfxSearchBarExample } from './generated/ifx-search-bar-example/ifx-search-bar-example';
import { IfxSearchFieldExample } from './generated/ifx-search-field-example/ifx-search-field-example';
import { IfxSelectExample } from './generated/ifx-select-example/ifx-select-example';
import { IfxSpinnerExample } from './generated/ifx-spinner-example/ifx-spinner-example';
import { IfxStatusExample } from './generated/ifx-status-example/ifx-status-example';
import { IfxStepperExample } from './generated/ifx-stepper-example/ifx-stepper-example';
import { IfxStepperCompactExample } from './generated/ifx-stepper-example-compact/ifx-stepper-example-compact';
import { IfxSwitchExample } from './generated/ifx-switch-example/ifx-switch-example';
import { IfxBasicTableExample } from './generated/ifx-basic-table-example/ifx-basic-table-example';
import { IfxTableDefaultStateExample } from './generated/ifx-table-example-defaultstate/ifx-table-example-defaultstate';
import { IfxTextareaExample } from './generated/ifx-textarea-example/ifx-textarea-example';
/* </AUTO-GENERATED-IMPORTS> */

@NgModule({
	declarations: [
		App,
		/* <AUTO-GENERATED-COMPONENTS> */
IfxAccordionExample,
		    IfxActionListExample,
		    IfxCardExample,
		    IfxCheckboxExample,
		    IfxCheckboxGroupExample,
		    IfxDatePickerExample,
		    IfxIndicatorExample,
		    IfxLinkExample,
		    IfxPaginationExample,
		    IfxProgressBarExample,
		    IfxRadioButtonExample,
		    IfxRadioButtonGroupExample,
		    IfxSearchBarExample,
		    IfxSearchFieldExample,
		    IfxSelectExample,
		    IfxSpinnerExample,
		    IfxStatusExample,
		    IfxStepperExample,
		    IfxStepperCompactExample,
		    IfxSwitchExample,
		    IfxBasicTableExample,
		    IfxTableDefaultStateExample,
		    IfxTextareaExample
		/* </AUTO-GENERATED-COMPONENTS> */
	],
	imports: [BrowserModule, InfineonDesignSystemModule.forRoot()],
	providers: [
		provideBrowserGlobalErrorListeners(),
	],
	bootstrap: [App],
})
export class AppModule {}
