import { isPlatformBrowser } from "@angular/common";
import {
	afterNextRender,
	Component,
	Inject,
	Injector,
	PLATFORM_ID,
	type OnInit,
	signal,
} from "@angular/core";
import Prism from "prismjs";
import "prismjs/components/prism-markup.js";
import "prismjs/components/prism-javascript.js";
import "prismjs/components/prism-typescript.js";

import packageJson from "../../package.json";

const declaredVersion =
	packageJson.dependencies["@infineon/infineon-design-system-angular"];

import { version as installedVersion } from "@infineon/infineon-design-system-angular/package.json";

@Component({
	selector: "app-root",
	templateUrl: "./app.html",
	standalone: false,
	styles: [],
})
export class App implements OnInit {
	protected readonly title = signal("angular-module-example");
	protected version = "";

	// default id
	private readonly defaultId = 
	/* <AUTO-GENERATED-DEFAULT-ID> */
"ifx-accordion-example"
	/* </AUTO-GENERATED-DEFAULT-ID> */;

	// current active example id
	protected activeId = signal(this.defaultId);

	constructor(private injector: Injector, @Inject(PLATFORM_ID) private platformId: object) {
		if (isPlatformBrowser(this.platformId)) {
			afterNextRender(
				() => {
					Prism.highlightAll();
				},
				{ injector: this.injector },
			);
		}
	}

	ngOnInit() {
		// Component initialization

		if (declaredVersion.includes("workspace")) {
			this.version = "workspace";
		} else {
			this.version = installedVersion;
		}

		if (!isPlatformBrowser(this.platformId)) return;

		const syncFromHash = () => {
			const next = this.getHashId();

			if (next) {
				this.activeId.set(next);
			} else if (!window.location.hash) {
				window.location.hash = `#${this.activeId()}`;
			}

			setTimeout(() => Prism.highlightAll(), 0);
		};

		syncFromHash();

		window.addEventListener("hashchange", syncFromHash);
	}

	private getHashId(): string {
		if (!isPlatformBrowser(this.platformId)) return "";
		return window.location.hash ? window.location.hash.substring(1) : "";
	}
}
