import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=15273%3A6407",
  {
    variant: { "Type": "Slider" },
    props: {
      captionLeft: figma.string("Caption Left"),
      captionRight: figma.string("Caption Right"),
      showLabel: figma.boolean("Show Label"),
      lIcon: figma.instance("L - Icon"),
      rIcon: figma.instance("R - Icon"),
      labelText: figma.string("Label Text"),
      text: figma.string("% Text"),
      type: figma.enum("Type", {
        Slider: "single",
        "Range-Slider": "double",
      }),
      showPercentage: figma.enum("Variant", {
        "+ Percentage": true,
      }),
      showCaption: figma.enum("Variant", {
        "+ Caption": html`left-text="Text" right-text="Text"`,
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      }),
      readOnly: figma.enum("State", {
        "Read-Only": true,
      }),
    },
    example: (props) => html`<ifx-slider min="0" max="100" step="1" value="50" show-percentage=${props.showPercentage} left-icon=${props.lIcon} right-icon=${props.rIcon} ${props.showCaption} type=${props.type} disabled=${props.disabled} >
    </ifx-slider>`,
  },
)

figma.connect(
  "https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=15273%3A6407",
  {
    variant: { "Type": "Range-Slider" },
    props: {
      captionLeft: figma.string("Caption Left"),
      captionRight: figma.string("Caption Right"),
      showLabel: figma.boolean("Show Label"),
      lIcon: figma.instance("L - Icon"),
      rIcon: figma.instance("R - Icon"),
      labelText: figma.string("Label Text"),
      text: figma.string("% Text"),
      type: figma.enum("Type", {
        Slider: "single",
        "Range-Slider": "double",
      }),
      showPercentage: figma.enum("Variant", {
        "+ Percentage": true,
      }),
      showCaption: figma.enum("Variant", {
        "+ Caption": html`left-text="Text" right-text="Text"`,
      }),
      disabled: figma.enum("State", {
        "Disabled": true,
      }),
      readOnly: figma.enum("State", {
        "Read-Only": true,
      }),
    },
    example: (props) => html`<ifx-slider min="0" max="100" step="1" min-value-handle="20" max-value-handle="80" show-percentage=${props.showPercentage} left-icon=${props.lIcon} right-icon=${props.rIcon} ${props.showCaption} type=${props.type} disabled=${props.disabled} >
    </ifx-slider>`,
  },
)
