# Deploys each PR under its own subfolder
name: Deploy PR preview Storybook

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-storybook-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install and Build
        run: |
          npm install
          npm run build:storybook

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        id: preview
        with:
          source-dir: ./storybook-static
          github-token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Get preview URL
        run: |
          echo "Preview URL: ${{ steps.preview.outputs.deployment-url }}"

      - name: Update comment in PR
        uses: actions/github@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            console.log("pr original message ", context.payload.pull_request.body);
            const newText = 'This is new text added to the comment.';
            const currentBody = context.payload.pull_request.body;
            if (!currentBody.includes(newText)) {
              const updatedBody = `${currentBody}\n${newText}`;
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: prNumber,
                body: updatedBody
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}