# Deploys each PR under its own subfolder
name: Deploy Vue preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          
      # - run: |
      #     cd examples/vue3-vite
      #     npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install and Build
        source-dir: ./examples/vue3-vite/dist
        run: |
          npm install
          npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./examples/vue3-vite/dist
          umbrella-dir: vue-app
