# Deploys each PR under its own subfolder
name: Deploy PR preview Vue app

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - examples/**
      
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install rsync 📚 # additional package needed to run github action locally in a docker container
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Install and Build
        run: |
          cd examples/vue3-vite
          npm i && npm run build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./examples/vue3-vite/dist
          umbrella-dir: pr-preview-vue-example
