name: PR Preview

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-preview-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  library-build-publish:
    uses: ./.github/workflows/shared-build-publish-libraries.yml
    with:
      snapshot: true
      snapshot-tag: pr
    secrets: inherit

  build-deploy-html-cdn-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: html-cdn-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  build-deploy-html-vite-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: html-vite-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  build-deploy-angular-module-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: angular-module-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  build-deploy-angular-standalone-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: angular-standalone-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  build-deploy-react-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: react-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  build-deploy-vue-example:
    needs: library-build-publish
    uses: ./.github/workflows/shared-build-deploy-examples.yml
    with:
      name: vue-example
      package-version: ${{ needs.library-build-publish.outputs.published-version }}
      deployment: pr

  comment-pr:
    needs: 
      - library-build-publish
      - build-deploy-html-cdn-example
      - build-deploy-html-vite-example
      - build-deploy-angular-module-example
      - build-deploy-angular-standalone-example
      - build-deploy-react-example
      - build-deploy-vue-example
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR with preview links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "PR Preview Links"
          message: |
            ### Preview Links for Deployed Examples
            - [HTML CDN Example](${{ needs.build-deploy-html-cdn-example.outputs.url }})
            - [HTML Vite Example](${{ needs.build-deploy-html-vite-example.outputs.url }})
            - [Angular Example (Module)](${{ needs.build-deploy-angular-module-example.outputs.url }})
            - [Angular Example (Standalone)](${{ needs.build-deploy-angular-standalone-example.outputs.url }})
            - [React Example](${{ needs.build-deploy-react-example.outputs.url }})
            - [Vue Example](${{ needs.build-deploy-vue-example.outputs.url }})

            Version: ${{ needs.library-build-publish.outputs.published-version }}