name: Build and Deploy Examples

on:
  workflow_call:
    inputs:
      package-version:
        required: true
        type: string
        description: 'Package version to use'
      name:
        required: false
        type: string
        description: 'Name of the example to build'
      deployment:
        required: false
        type: string
        description: 'Deployment target (pr, production, none)'
        default: 'pr'
    outputs:
      deployment-url:
        description: "Deployed URL"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ inputs.package-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Enable corepack and install pnpm
        run: |
          corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      
      - name: Update ${{ inputs.name }} to use published version
        run: |
          pnpm run --filter='${{ inputs.name }}' cicd-update-version
      
      - name: Install dependencies
        run: pnpm install --filter='${{ inputs.name }}' --no-frozen-lockfile
      
      - name: Build ${{ inputs.name }} example
        run: |
          pnpm --filter='${{ inputs.name }}' build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-build
          path: examples/${{ inputs.name }}/dist/
          retention-days: 1

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:     
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}-build
          path: deploy-files/
      
      - name: Deploy PR Preview
        if: ${{ inputs.deployment == 'pr' }}
        id: deploy-pr
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: deploy-files/
          preview-branch: gh-pages-preview
          umbrella-dir: pr-preview-${{ inputs.name }}

      - name: Deploy to Production
        if: ${{ inputs.deployment == 'production' }}
        id: deploy-prod
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy-files/
          destination_dir: ${{ inputs.name }}
    outputs:
      url: ${{ steps.deploy-pr.outputs.deployment-url || '' }}

  collect-outputs:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    steps:        
      ## Write urls matrix outputs workaround 
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: collect-matrix-outputs
        with:
          matrix-step-name: build-and-deploy-examples
          matrix-key: ${{ matrix.app.name }}
          outputs: |
            name: ${{ matrix.app['pretty-name'] }}
            url: ${{ steps.deploy.outputs.deployment-url }}
