name: Deploy Stencil Web components Library to NPM

on:
  push:
    branches:
     - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize # canary on new commit
 
env:
  CANARY_VERSION: ${{ steps.build-stencil.outputs.CANARY_VERSION }}

jobs:
  stencil-library-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')" # job will not run, if triggered via ship-it
    outputs:
      version: ${{ steps.build-stencil.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags for ship-it

      - name: download + setup auto
        uses: auto-it/setup-auto@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Build stencil
        id: build-stencil
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        run: | 
          cd packages/components
          npm install
          npm run build:stencil
          CANARY_VERSION=$(auto shipit --dry-run --quiet)
          echo "Publishing: $CANARY_VERSION"
          echo "canary_version=$CANARY_VERSION" >> $GITHUB_OUTPUT
          auto shipit

      - name: Create Release for react wrapper # releasing as npm package
        id: release-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CANARY_VERSION: ${{ env.CANARY_VERSION }}

        run: | 
          cd packages/components-react
          npm install @infineon/infineon-design-system-stencil@"$CANARY_VERSION"
          echo $CANARY_VERSION
          npm version $CANARY_VERSION --no-git-tag-version --force
          npm run build
          npm publish --tag canary


          