name: Run e2e tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize # canary on new commit
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags for ship-it
      - name: Clean working directory
        run: git clean -fdx

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Run tests # releasing as a github npm package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: | 
          npm install
          npm run test
